### ISSUE TITLE
transpile: Init list not implemented for Uint

### ISSUE THREAD

**Issue by spernsteiner** [immunant/c2rust#1009]
```C
int f() {
    unsigned x = { 1 };
    return x;
}

int g() {
    int x = { 1 };
    return x;
}
```

Translation of `g` succeeds.  Translation of `f` fails, complaining "Init list not implemented for Uint", and `f` is omitted from the generated Rust code.

**Comment by kkysen** [comment]
I think the fix to support any scalar type should be pretty trivial.
