### ISSUE TITLE
Refactorer: Transformer ignores lints

### ISSUE THREAD

**Issue by TheDan64** [immunant/c2rust#101]
For example, trying to transform on
```rust
#![allow(mutable_transmutes)]
fn foo() {
    unsafe { *::std::mem::transmute::<&[u8; 6], &mut [u8; 6]>(b"foobar") };
}
```

will fail to compile even though the lint allows it. The ast is preserved, however, and the lint will still be present in the resulting output in a no-op transform.

**Comment by rinon** [comment]
Fixed in 14848e847887a516bb11a880774cbb97fc7d9453
