### ISSUE TITLE
Installing from git fails

### ISSUE THREAD

**Issue by thedrow** [immunant/c2rust#107]
I needed the changes in https://github.com/immunant/c2rust/commit/44d3eb5ecc5b458e0255b3b1c98badde4e0b5267 to transpile libdivide and tried installing from git using:
```
LLVM_CONFIG_PATH=/home/linuxbrew/.linuxbrew/opt/llvm/bin/llvm-config cargo +nightly-2019-04-12 install --git https://github.com/immunant/c2rust.git
```

But I got the following error:
```
    Updating git repository `https://github.com/immunant/c2rust.git`
error: failed to update submodule `ReMon`

Caused by:
  invalid url `git@github.com:stijn-volckaert/ReMon.git`: relative URL without a base
```

**Comment by rinon** [comment]
Sorry, we always have a git ssh key set up for github, so this was never an issue. Should be fixed in ffb7e52de16d37fbd32a410c8d55605a48dbca76

**Comment by thedrow** [comment]
This still happens.

```
Caused by:
  failed to update submodule `gumbo_snudown`

Caused by:
  invalid url `git@github.com:JordanMilne/gumbo-parser.git`: relative URL without a base
```

**Comment by thedrow** [comment]
@rinon ping?

**Comment by thedataking** [comment]
Turns out that `.gitmodules` in the snudown submodule was also set to use ssh, should be fixed now. Can you give it another shot and let me know if the issue is resolved @thedrow?

**Comment by thedrow** [comment]
Please reopen:
```
LLVM_CONFIG_PATH=/home/linuxbrew/.linuxbrew/opt/llvm/bin/llvm-config cargo +nightly-2019-04-12 install --git https://github.com/immunant/c2rust.git
    Updating git repository `https://github.com/immunant/c2rust.git`
error: multiple packages with binaries found: c2rust, c2rust-manual-preprocessors, c2rust-xcheck-backend-zstd-logging, c2rust-xcheck-pointer-tracer, fibo, robotfindskitten
```

**Comment by thedataking** [comment]
@thedrow can you try `LLVM_CONFIG_PATH=/home/linuxbrew/.linuxbrew/opt/llvm/bin/llvm-config cargo +nightly-2019-04-12 install --git https://github.com/immunant/c2rust.git c2rust`?

That worked for me (using the host OS clang/LLVM package; not Linuxbrew).

**Comment by thedrow** [comment]
Yes. That works.
