### ISSUE TITLE
Casting bool to pointer type results in invalid Rust

### ISSUE THREAD

**Issue by jorendorff** [immunant/c2rust#1077]
The fix should be the same as #1030, but presumably with something like `size_t` as the intermediate type.

(Why, you might ask, would anyone ever do this in real code. The answer is that C doesn't have generics, so projects will have, say, a single hash table type with `void *` values, and store booleans in it by casting.)

**Comment by fw-immunant** [comment]
This code reproduces this bug:
```C
#include <stdbool.h>

void f(bool b) {
    void* x = (void*)b;
}
```
It gets translated to:
```rust
#[no_mangle]
pub unsafe extern "C" fn f(mut b: bool) {
    let mut x: *mut libc::c_void = b as *mut libc::c_void;
}
```
which does not compile (E0606).
