### ISSUE TITLE
ast_exporter can't convert a c code to ast

### ISSUE THREAD

**Issue by hong-code** [immunant/c2rust#1080]
ast_exporter be built successfully, however it can't generate ast.

the code errors : "c2rust-transpile: /home/c2rust/c2rust-ast-exporter/src/AstExporter.cpp:2793: Outputs process(int, const char**, int*): Assertion `outputs.size() == 1 && "Expected exactly one output."' failed."

I using debug json :        {
            "type": "lldb",
            "request": "launch",
            "name": "Debug executable 'c2rust-transpile'",
            "cargo": {
                "args": [
                    "build",
                    "--bin=c2rust-transpile",
                    "--package=c2rust"
                ],
                "filter": {
                    "name": "c2rust-transpile",
                    "kind": "bin"
                }
            },
            "args": ["/home/EvilStrGen/build/compile_commands.json"],
            "cwd": "${workspaceFolder}"}

**Comment by fw-immunant** [comment]
Can you provide the contents of the `compile_commands.json` you're using?

**Comment by hong-code** [comment]
I have already solved this problem, maily due to my negligence, I use c2rust to translate c++code to rust, which is not supported by c2rust.
