### ISSUE TITLE
libsyntax not found on macOS

### ISSUE THREAD

**Issue by Kixunil** [immunant/c2rust#12]
When attempting to run `ast-importer` I get this message:

```
dyld: Library not loaded: @rpath/libsyntax-5b61bedd79cd3694.dylib
  Referenced from: /<redacted>/c2rust/ast-importer/target.<redacted>/release/./ast_importer
  Reason: image not found
Abort trap: 6
```

**Comment by glguy** [comment]
Try using `cargo run` or using the script in `scripts/transpiler.py`. The way that rust builds libraries you have to manually specify the library load path to run the executables.

**Comment by glguy** [comment]
Probably because we're using *rustc* internal version of libsyntax, running ast-importer without `cargo run` requires a bit of extra work.

```
LD_LIBRARY_PATH=$(rustc --print sysroot)/lib ast-importer/target/debug/ast_importer
```
will get it running if you want to do it manually.
