### ISSUE TITLE
Multiple C sources with the same name cause `c2rust` to skip transpiling

### ISSUE THREAD

**Issue by lopopolo** [immunant/c2rust#126]
I'm attempting to transpile a project that has support for compile time add in modules. These modules all live in their own directories and have an `init.c` in them. When transpiling, `c2rust` tries to output all of these to the same `init.rs`, skips them, and thinks the build is incremental.

**Comment by thedataking** [comment]
Thanks for opening an issue. Some projects build the same source files twice (e.g. to support shared and static libraries). We can add a `allow-duplicates` switch and keep the current behavior or allow duplicates by default (adding a `skip-duplicates` option in this case). Curious if you have any thoughts on this.

**Comment by lopopolo** [comment]
I don't have a preference in terms of flags, but would bias toward backwards compatibility. I can easily add a new switch to the transpilation of my library.

I would like to point out that both `init.c` sources are functionally different and the resulting Rust filenames would have to be disambiguated somehow.

**Comment by ahomescu** [comment]
This should work on the latest master when using `--output-dir` and `--emit-build-files`. Each `init.rs` file should go into its own directory, if the original `init.c` files were separate too.

**Comment by kkysen** [comment]
@ahomescu, was this fixed a long time ago?

**Comment by ahomescu** [comment]
I think so, is it broken again? If not, we can close the bug.

**Comment by thedataking** [comment]
+1 for closing this bug; IIRC, this was fixed.
