### ISSUE TITLE
support for stable?

### ISSUE THREAD

**Issue by ng-0** [immunant/c2rust#132]
Hi,

Are there any plans to support rust release instead of (or in addition to) nightly in the future?

**Comment by thedataking** [comment]
Two main things prevent us from supporting stable at the moment: 
- The Rust code we output needs to use nightly features. We track the features we need in issue https://github.com/immunant/c2rust/issues/46. 
- Secondly, the implementation of our tools uses internal Rust compiler APIs only exposed in nightlies.

**Comment by ng-0** [comment]
Thanks!
