### ISSUE TITLE
Ownership analysis marks field read on write

### ISSUE THREAD

**Issue by TheDan64** [immunant/c2rust#138]
Ownership analysis will generate this code:
```rust
struct SizedData {
    #[ownership_static(READ)]
    buf: *mut u32,
    #[ownership_static()]
    bsize: usize,
}

#[ownership_mono("", WRITE)]
#[ownership_constraints(le(WRITE, _0))]
unsafe fn init_buf(sd: *mut SizedData) -> i32 {
    let mut buf: *mut u32 = 0 as *mut u32;

    buf = malloc((*sd).bsize as libc::c_ulong) as *mut u32;

    if buf.is_null() {
        return 1;
    }

    *buf.offset(0) = 1;

    (*sd).buf = buf;

    return 0;
}
```

But the field `buf` shouldn't be `READ` when it's clearly written to?

**Comment by rinon** [comment]
It's never written to after its in the struct, in this example. I.e. the struct could contain a read-only borrow, if the buf was kept alive longer than the struct.

**Comment by TheDan64** [comment]
Right - it's the mutability of the ptr itself, not the field that counts.
