### ISSUE TITLE
Ever-changing randomized translations

### ISSUE THREAD

**Issue by danielrh** [immunant/c2rust#14]
If I run ~/c2rust/scripts/transpile.py $PWD/compile_commands.json 
the result is different  upon each run.
This makes it very difficult to tell what has changed in the translations, especially if I'm trying to apply subtle changes to the C code in order to get a desired output in the transpiled rust

**Comment by glguy** [comment]
I think this is related to (possible among other things) relying on the order of items stored in HashMaps in relooper. Can you be more specific about what changes you're seeing?

**Comment by danielrh** [comment]
Running c2rust twice on https://github.com/danielrh/zstd/tree/c2rust results in 2 different outputs for the same code

here are two runs. No code was changed between the run-- c2rust was simply executed twice on the same code and the results have significant differences-- some types even get different names (eg postfixed with `_0`) and there are even some indentation differences, probably due to unique wrapping from type name differences, which can make it hard to version control or upstream fixes/updates.


[firstrun.zip](https://github.com/immunant/c2rust/files/2173449/firstrun.zip)
[secondrun.zip](https://github.com/immunant/c2rust/files/2173450/secondrun.zip)

**Comment by danielrh** [comment]
it might be desirable to avoid enforcing any line limitations on transpiled code, to avoid difficult merges.
My understanding is that `golang`'s autoformatter doesn't ever wrap lines, partially so that line numbers stay the same before and after running their fmt tool. If users want to wrap the lines of their code, they may wish to use a separate commit hook to do so.

**Comment by TheDan64** [comment]
If iteration of hash maps are an issue, we could try swapping in https://github.com/bluss/indexmap which is basically an insertion order preserving hash map.

**Comment by glguy** [comment]
I think this is fixed for both type declarations and for relooper. We just need to get the commits synced.

**Comment by thedataking** [comment]
Commits are synced. @danielrh feel free to reopen if this is still an issue.
