### ISSUE TITLE
Is this 'mirror repository' ok? Did them get your permission?

### ISSUE THREAD

**Issue by KaneGreen** [immunant/c2rust#140]
I found a 'open source software' [on 'oschina.net'](https://www.oschina.net/p/c2rust-).
And the 'mirror repository' is stored [on 'gitee.com'](https://gitee.com/mirrors/C2Rust).

* 'mirror repository' on 'gitee.com' is almost the same as it on GitHub. It is said for user to download the code faster. And the 'mirror repository' will 'pull' from GitHub once a day.
* However, 'open source software' on 'oschina.net' is submited by a user with the ID of ['terenceyhj'](https://my.oschina.net/terence). 

I can't figure out whether them get your permission before they mirror the repository.

**Comment by rinon** [comment]
No, these are not official mirrors. C2Rust is released under the BSD license, which does permit re-publication as long as the license and copyright are preserved. As long as no one else is claiming they own or wrote the software, then they are allowed to redistribute it. Thanks for bringing this to our attention.
