### ISSUE TITLE
[Feature request] Add support for windows

### ISSUE THREAD

**Issue by crlf0710** [immunant/c2rust#144]
Tried to build under windows and most errors encountered are llvm errors. So maybe llvm is needed to build from source for msvc. Project c2rust will definitely be a useful tool!

**Comment by rinon** [comment]
We haven't worked on Windows support at all. It should be possible, but has been low priority for us. Most Windows code is C++, so I'm not sure how useful translating C will be for Windows. We'd welcome any pull requests to add Windows support, though.

**Comment by XVilka** [comment]
You can enable the Windows platform for Azure Pipelines and allow failures, work slowly towards the build.

**Comment by mmacedoeu** [comment]
Almost got it to work, looks like in some script it is calling make instead of msvc equivalent
