### ISSUE TITLE
Ownership annotations may panic with 'new and reprinted ASTs don't match'

### ISSUE THREAD

**Issue by TheDan64** [immunant/c2rust#148]
```rust
fn test(#[nonnull] z: *mut u8) {
    *z = 1u8;
}
```

```lua
refactor:run_command("select", {"target", "crate; desc(fn || field);"})
refactor:run_command("ownership_annotate", {"target"})
```

This seems to be a problem with param annotations

**Comment by rinon** [comment]
This was fixed upstream in https://github.com/rust-lang/rust/commit/dd987275418cb23809c2521e31686013a59ea061 but we can't roll to the new nightly yet due to changes in the pretty printer API. Will see if we can get more visibility for the pretty printer.

**Comment by rinon** [comment]
Waiting on #165

**Comment by TheDan64** [comment]
@rinon this is fixed now, right?

**Comment by rinon** [comment]
Yeah
