### ISSUE TITLE
Transpiled code for function pointers that take an unspecified number of parameters does not compile

### ISSUE THREAD

**Issue by lopopolo** [immunant/c2rust#149]
Function type declarations that have an empty (not `void`) argument list take an unspecified number of arguments of unspecified types. C2Rust incorrectly transpiles functions defined this way to a Rust function type that takes no arguments.

Here is an example of a declaration from oniguruma:

https://github.com/kkos/oniguruma/blob/df943f4d634057ea58a6ab154b1bac8768f1897c/src/st.h#L19-L22

```c
struct st_hash_type {
    int (*compare)();
    int (*hash)();
};
```

oniguruma uses this struct to implement generics. Instances of this struct are created like:

https://github.com/kkos/oniguruma/blob/df943f4d634057ea58a6ab154b1bac8768f1897c/src/st.c#L38-L50

```c
static int numcmp(long, long);
static int numhash(long);
static struct st_hash_type type_numhash = {
    numcmp,
    numhash,
};

/* extern int strcmp(const char *, const char *); */
static int strhash(const char *);
static struct st_hash_type type_strhash = {
    strcmp,
    strhash,
};
```

**Comment by rinon** [comment]
For K&R function pointers we cast back and forth to the right signature at stores and loads, but it looks like some loads aren't getting cast before use. I'll look into this, thanks.

**Comment by rinon** [comment]
Oniguruma transpiles and compiles in Rust for me now. The const macro conversion option doesn't work for oniguruma yet, but I'll look into that.

**Comment by lopopolo** [comment]
@rinon can you cc me on that ticket? I'm very interested in transpiling oniguruma

**Comment by lopopolo** [comment]
Thank you for closing out this ticket 💪
