### ISSUE TITLE
Ownership analysis panics with "no solution found"

### ISSUE THREAD

**Issue by TheDan64** [immunant/c2rust#172]
```rust
pub type size_t = libc::c_ulong;

extern "C" {
    #[no_mangle]
    fn _buf_findstr(str: *const libc::c_char, buf: *mut *mut libc::c_char,
                    buf_len: *mut size_t) -> libc::c_int;
}

pub unsafe extern "C" fn envz_entry(mut envz: *const libc::c_char,
                                    mut envz_len: size_t,
                                    mut name: *const libc::c_char)
 -> *mut libc::c_char {
    let mut buf_ptr: *mut libc::c_char = envz as *mut libc::c_char;
    let mut buf_len: size_t = envz_len;
    while buf_len != 0 {
        if _buf_findstr(name, &mut buf_ptr, &mut buf_len) != 0 {
            if !buf_ptr.is_null() {
                if *buf_ptr as libc::c_int == '=' as i32 ||
                       *buf_ptr as libc::c_int == '\u{0}' as i32 {
                    buf_ptr = buf_ptr.offset(-1);
                    /* Move buf_ptr back to start of entry. */
                    while *buf_ptr as libc::c_int != '\u{0}' as i32 &&
                              buf_ptr != envz as *mut libc::c_char {
                        buf_ptr = buf_ptr.offset(-1)
                    }
                    if *buf_ptr as libc::c_int == '\u{0}' as i32 {
                        buf_ptr = buf_ptr.offset(1)
                    }
                    return buf_ptr
                }
            }
        }
    }
    return 0 as *mut libc::c_char;
}
```

**Comment by rinon** [comment]
Isn't this just another `extern` function that needs `WRITE` instead of `MOVE` constraints? I should probably see if we can't get a better error message for that case.

**Comment by TheDan64** [comment]
Last time it didn't panic, it just generated incorrect results by being `MOVE` instead of `WRITE` - so no, I don't think so?

**Comment by rinon** [comment]
Hmmm, ok, yeah. I'll look into it more then.

**Comment by rinon** [comment]
It appears that the problem is indeed constraints. Adding `#[ownership_constraints(le(WRITE, _2), le(_2, WRITE))]` to `_buf_findstr` results in a valid solution. I can't figure out why that can't be `READ`, since findstr doesn't write to the inner pointer, but it doesn't work. Might be because it needs to return a writable pointer?

**Comment by rinon** [comment]
I think the correct constraints are actually: `#[ownership_constraints(le(WRITE, _1), le(_1, WRITE), le(READ, _2), le(_2, READ))]`. With only the inner pointer, ownership analysis thinks that `_buf_findstr` should be `str: &char, buf & &mut char, buf_len: &size_t`
