### ISSUE TITLE
convert_knr_function fails on libxml2

### ISSUE THREAD

**Issue by rinon** [immunant/c2rust#176]
`thread 'main' panicked at 'ctype parameter must be a function instead of TypeOf(CTypeId(96))', c2rust-transpile/src/convert_type.rs:459:29`
when transpiling libxml2

**Comment by ahomescu** [comment]
Commit https://github.com/immunant/c2rust/commit/f07d6d1f5cf59bf7e41e45731e20d5162e07d2fe should fix this.
