### ISSUE TITLE
Run rustfmt on the output?

### ISSUE THREAD

**Issue by anp** [immunant/c2rust#18]
As the project moves towards designing the post-processing steps for the tool, would you consider adding a rustfmt step before writing the output? I think it would help to have a more human-friendly starting point after the initial conversion process.

**Comment by glguy** [comment]
We already run `rustfmt` on the output in the test harness, I don't see why we shouldn't run it in `transpiler.py`

**Comment by thedataking** [comment]
Fixed in 6684fa90910a785280dc73d63b2f13448399e174 (available after next sync).
