### ISSUE TITLE
Pointer rewriting script known limitations

### ISSUE THREAD

**Issue by TheDan64** [immunant/c2rust#180]
* Void pointers
* Most pointer casts
* Multi-level pointers
* Negative pointer offsets
* Pointers as indexes (`if ptr1 > ptr2`)
* Return pointers currently unsupported: https://github.com/immunant/c2rust/issues/168
* Complex lifetimes (ie linked list manipulation)
* Non-int mallocs (ie struct mallocs)

**Comment by kkysen** [comment]
Closing as `c2rust refactor` in its current form is no longer being developed.
