### ISSUE TITLE
Reorg removes required import

### ISSUE THREAD

**Issue by TheDan64** [immunant/c2rust#206]
In this very small mod block:
```rust
pub mod wchar_h {
    #[src_loc = "86:1"]
    pub type mbstate_t = _mbstate_t;
    use super::_types_h::_mbstate_t;
    /* _WCHAR_H_ */
}
```
from https://github.com/immunant/newlib-rs/blob/786b327543ce631ab48d7881ab97d5c8dd4a4d20/src/stdlib/wctomb_r.rs#L434-L435

the use block gets removed, and so you get a compiler error about the missing type

**Comment by rinon** [comment]
e0ca9eaa77ebd314eb69bdd75a6713ac3b4d9fb7 should have fixed this, but involved changes to the transpiler as well as the refactorer. Did you re-transpile?

**Comment by TheDan64** [comment]
I believe I did, but I'll retry

**Comment by TheDan64** [comment]
Yes, this issue still exists. I do believe https://github.com/immunant/c2rust/commit/e0ca9eaa77ebd314eb69bdd75a6713ac3b4d9fb7 fixed the previous (and similar) issue, though.

**Comment by TheDan64** [comment]
Seems to have been fixed by one of the other changes

**Comment by TheDan64** [comment]
So the issue with `mbstate_t` is fixed, but there's another similar import issue so I'll just re-open this ticket

**Comment by TheDan64** [comment]
This static: https://github.com/immunant/newlib-rs/blob/reorganized/src/stdlib/arc4random.rs#L762
```rust
pub static mut _arc4random_data: C2RustUnnamed =
    C2RustUnnamed{rs: _rs{rs_have: 0, rs_count: 0,},
                  rsx:
                      _rsx{rs_chacha: chacha_ctx{input: [0; 16],},
                           rs_buf: [0; 1024],},};
```
gets it's own type `C2RustUnnamed` resolved correctly to `crate::src::stdlib::arc4random::C2RustUnnamed` but the inner types, `_rs` and `_rsx`'s import goes missing. Prior to reorg, there was a `use super::{_rs, _rsx};` in the same mod block but is now removed

**Comment by rinon** [comment]
Heh, `ExprKind::Struct` has a `Path` field that I missed, only checked `ExprKind::Path` for local idents we need to keep. Easy fix, will push now.
