### ISSUE TITLE
Reorg incorrectly merges different structures with same name from different headers

### ISSUE THREAD

**Issue by ahomescu** [immunant/c2rust#207]
ioq3 contains [two](https://github.com/immunant/ioq3/blob/master/code/opus-1.2.1/celt/mdct.h#L49) [versions](https://github.com/immunant/ioq3/blob/master/code/libvorbis-1.3.6/lib/mdct.h#L55) of `struct mdct_lookup` which are completely different (but both defined in headers named `mdct.h`). When running reorg on ioq3, it pulls the libvorbis version of `mdct_lookup` into `opus_1_2_1/celt/mdct.rs` instead of the local one, which is completely wrong and refuses to compile.

**Comment by ahomescu** [comment]
Additionally, ioq3 also contains [two](https://github.com/immunant/ioq3/blob/master/code/opus-1.2.1/celt/mdct.c) [versions](https://github.com/immunant/ioq3/blob/master/code/libvorbis-1.3.6/lib/mdct.c) of `mdct.c`.

**Comment by TheDan64** [comment]
Maybe related to https://github.com/immunant/c2rust/issues/204?

**Comment by ahomescu** [comment]
Fixed in 4948d823.
