### ISSUE TITLE
Reorg doesn't merge types correctly due to type alias

### ISSUE THREAD

**Issue by TheDan64** [immunant/c2rust#209]
Running reorg on newlib nets you this error:
```rust
error[E0606]: casting `&mut _types_h::mbstate_t` as `*mut src::stdio::findfp::_types_h::_mbstate_t` is invalid
  --> src/stdio/findfp.rs:69:29
   |
69 |     crate::string_h::memset(&mut (*ptr)._mbstate as *mut _mbstate_t as *mut libc::c_void,
   |   
```

`_mbstate_t` in https://github.com/immunant/newlib-rs/blob/279c2fa5c4971f6b532159574cda8c72c5356620/src/stdio/findfp.rs#L50-L53 is a struct:

```rust
pub struct _mbstate_t {
    pub __count: libc::c_int,
    pub __value: C2RustUnnamed,
}
```

but after reorg it creates a new file `src/_types_h.rs` (doesn't exist prior) which has `_mbstate_t` as a type alias to the struct `mbstate_t`:
```rust
#[repr(C)]
#[derive(Copy, Clone)]
pub struct mbstate_t {
    pub __count:  libc::c_int,
    pub __value:  crate::_types_h::C2RustUnnamed,
}
pub type _mbstate_t =  crate::_types_h::mbstate_t;
```

Multiple other files (prior to reorg) have this type alias, but doesn't merge the one in `findfp.rs` because it lacks the type alias and directly has the struct instead

**Comment by ahomescu** [comment]
I wonder if this is the issue https://github.com/immunant/c2rust/blob/master/c2rust-refactor/src/context.rs#L475? I noticed this yesterday and wondered if it's correct for `structural_eq` to always return `true` for type aliases.

**Comment by rinon** [comment]
I don't think it's that, I think it's the opposite Structs should merge with type aliases to the same struct, which isn't happening

**Comment by ahomescu** [comment]
Is this a duplicate or related to #206?

**Comment by TheDan64** [comment]
I don't believe so

**Comment by TheDan64** [comment]
Maybe related
