### ISSUE TITLE
Options to elide literal types in more places

### ISSUE THREAD

**Issue by anp** [immunant/c2rust#21]
The current output has many unnecessary explicit type declarations, especially for literal values. A simple example from the homepage:

`let mut i: libc::c_int = 1i32;`

While this is useful for cross-verifying one's C code, it would be nice to only have (at max) one type annotation on this line, since only one is necessary for the code to be correct.

**Comment by TheDan64** [comment]
This is a good point; there are a bunch of type annotations that don't really add value such as (non function) null pointers and struct initializers which type inference would do fine with:

```rust
let mut x: *mut MyStruct = 0 as *mut MyStruct;
let mut y: MyStruct = MyStruct { ... };
```

**Comment by TheDan64** [comment]
@anp I've added a flag `--reduce-type-annotations` as of 14223c6a58bec57f1a90f186930ff7c5b8595b28 to the `ast-importer` which can be used for this purpose. Here is an example of local variables, some of which will have no explicit type annotation when the flag is passed:

```c
int a;
int b = 0;
int c = foo();
struct MyStruct d = {0};
int *e = 0;
```

which becomes:

```rust
let mut a: libc::c_int = 0;
let mut b = 0i32;
let mut c = foo();
let mut d = MyStruct{i: 0i32,};
let mut e = 0 as *mut libc::c_int;
```
