### ISSUE TITLE
[reorg] Replaced extern array types should never be cast back to zero-length arrays

### ISSUE THREAD

**Issue by rinon** [immunant/c2rust#210]
Running reorg over nginx results in several of the following errors:

    error[E0606]: casting `&mut [src::src::core::ngx_conf_file::ngx_conf_bitmask_t; 4]` as `*mut [src::src::core::ngx_conf_file::ngx_conf_bitmask_t; 0]` is invalid
    --> src/src/http/modules/ngx_http_fastcgi_module.rs:5924:36
         |
    5924 | / ...                   &mut crate::src::src::http::ngx_http_upstream::ngx_http_upstream_cache_method_mask as
    5925 | | ...                       *mut [crate::src::src::core::ngx_conf_file::ngx_conf_bitmask_t; 0] as
         | |____________________________________________________________________________________________^

**Comment by rinon** [comment]
Fixed indirectly via ae69ce4df6da3228f2f3fc109e0cdfacbf1bcf96

**Comment by ahomescu** [comment]
I had to revert the commit, since it broke ioq3.
