### ISSUE TITLE
[reorg] Handle conflicting items with the same name

### ISSUE THREAD

**Issue by ahomescu** [immunant/c2rust#212]
ioq3 contains [two](https://github.com/immunant/ioq3/blob/master/code/libvorbis-1.3.6/lib/mdct.h#L55) [different](https://github.com/immunant/ioq3/blob/master/code/opus-1.2.1/celt/mdct.h#L49) definitions of the `mdct_lookup` structure. The refactorer handles this by unifying the first one with all its copies, then deciding the second definition conflicts, and leaving all its definitions in-place without any merges.

We then run into problems later when other items get unified but each pointing to a different copy of the second `mdct_lookup` (the one from `celt/mdct.h`), which causes compile errors. For example, we get:
```Rust
// In `mdct.rs`, uses `mdct_lookup` from the current file
pub unsafe extern "C" fn clt_mdct_backward_c(
    mut l: *const mdct_lookup,
...

// In `modes.rs`
pub struct OpusCustomMode {
    ...
    // Uses the `mdct_lookup` from the current file, not the one from `mdct.rs`
    pub mdct: mdct_lookup,
    ..
}

// In `celt_decoder.rs`, uses `OpusCustomMode` above
unsafe extern "C" fn celt_synthesis(
    mut mode: *const crate::src::opus_1_2_1::celt::modes::OpusCustomMode,
...
        while b < B {
            crate::src::opus_1_2_1::celt::mdct::clt_mdct_backward_c(
                &(*mode).mdct,
...
```

In the example above, the call site passes a value of type `modes::mdct_lookup` into a callee which expects a `mdct::mdct_lookup`, and the two structures are different (albeit structurally identical).

**Comment by rinon** [comment]
Fixed in d20ea3e98cee97400c10b3d12eae4f5aff5ad409
