### ISSUE TITLE
Unimplemented builtins __builtin_assume_aligned & __builtin_unwind_init

### ISSUE THREAD

**Issue by crlf0710** [immunant/c2rust#218]

**Comment by rinon** [comment]
Thanks for the report. Guessing these are new clang 9 builtins. Do you have code to produce these?

**Comment by crlf0710** [comment]
Yes, there's one instance here:
https://github.com/emacs-mirror/emacs/blob/emacs-26.3/src/lisp.h

**Comment by TheDan64** [comment]
`__builtin_assume_aligned` no longer breaks. Since this is a pointer optimization hint that we can't replicate in rust, we just pass the pointer input in its place.
