### ISSUE TITLE
Correctly parse the GCC labels-as-values code

### ISSUE THREAD

**Issue by XVilka** [immunant/c2rust#221]
```c
static const int array[] = { &&foo - &&foo, &&bar - &&foo,
                             &&hack - &&foo };
goto *(&&foo + array[i]);
```

See the official documentation here https://gcc.gnu.org/onlinedocs/gcc/Labels-as-Values.html

**Comment by thedataking** [comment]
Hi Anton, so far we have found ways to disable labels-as-values for Python and Ruby. Did you come across some code where it couldn't be disabled?

**Comment by thedataking** [comment]
Thanks for letting me know. In that case, we'll close this issue until we run into a codebase where we absolutely need support for this extension. Feel free to reopen if/when that happens.
