### ISSUE TITLE
`c2rust refactor` expands rust macros

### ISSUE THREAD

**Issue by samuela** [immunant/c2rust#223]
I just ran `c2rust refactor link_funcs --cargo --rewrite-mode inplace` which is an awesome command but unfortunately it also made some "very wrong" changes to my sources. For example,

```rust
// My comment.
assert!(mycondition);
```
became
```rust
if !mycondition {
  {
    ::std::rt::begin_panic(
      "assertion failed: mycondition",
      &("applets/applet_tables.rs", 5467u32, 5u32),
    )
  }
}
```
which produces an error:
```
error[E0658]: use of unstable library feature 'libstd_sys_internals': used by the panic! macro
   --> applets/applet_tables.rs:992:9
    |
992 |         ::std::rt::begin_panic(
    |         ^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add `#![feature(libstd_sys_internals)]` to the crate attributes to enable
```

In addition, code like
```rust
    #[cfg(feature = "xzcat")]
    appy_mcappface.push(bb_applet {
      name: "xzcat",
      main: "unxz",
      entrypoint: unxz_main,
      install_loc: InstallLoc::DIR_USR_BIN,
      need_suid: SUID::SUID_DROP,
      noexec: false,
      nofork: false,
      usage: std::include_str!("../usage/xzcat"),
    });
```
is deleted completely when the feature flag is not listed as a default! This seems like subtly pernicious behavior that the authors of large-scale refactoring changes could very easily miss.

**Comment by rinon** [comment]
Macros such as `assert` and `cfg` are not well-supported in the refactorer (yet). We'll look into this, but it's not going to be a quick fix, unfortunately.

**Comment by kkysen** [comment]
Closing as `c2rust refactor` in its current form is no longer being developed.
