### ISSUE TITLE
cannot access a scoped thread local variable without calling `set` first when compiling sqlite

### ISSUE THREAD

**Issue by tupshin** [immunant/c2rust#226]
step to reproduce:
download and unzip 
https://www.sqlite.org/2019/sqlite-autoconf-3300100.tar.gz

./configure
intercept-build make
c2rust transpile compile_commands.json

**Comment by rinon** [comment]
Are you using the crates.io release of c2rust? If so, can you try building from master? That should have been fixed in 575dafdea856ec9ff5d9f27063d381dd74d54dc5 (I hit the same issue).

**Comment by tupshin** [comment]
I was. Thanks. Giving a build from master a try now.

**Comment by tupshin** [comment]
Inded confirmed fixed. Thanks
