### ISSUE TITLE
Doesn't build with nightly-2020-01-31

### ISSUE THREAD

**Issue by berkus** [immunant/c2rust#233]
```
error[E0463]: can't find crate for `syntax_pos`
 --> github.com-1ecc6299db9ec823/c2rust-ast-builder-0.14.0/src/lib.rs:5:1
  |
5 | extern crate syntax_pos;
  | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `c2rust-ast-builder`.
```

```
➤ rustc --version
rustc 1.42.0-nightly (cd1ef390e 2020-01-31)
```

**Comment by thedataking** [comment]
Hi @berkus!

C2Rust depends on the internals of the rust compiler which are undergoing frequent change so we cannot support any recent nightly release (sorry if that was not sufficiently clear in the README). Therefore, you are expected to use the `nightly-2019-12-05` release. This version should be selected automatically by the `rust-toolchain` file if you are building from the master branch. Hope this helps!

**Comment by berkus** [comment]
Ah, my bad, thanks!

**Comment by berkus** [comment]
The build failed because I was installing it using `cargo`, jfyi anyone finding this ticket later.

**Comment by TheDan64** [comment]
You can install with cargo, you just have to tell it to use the correct nightly

**Comment by berkus** [comment]
Yes, I had it running with cargo default, which didn't go well.

I wonder if it's possible to specify toolchain version per-installed-package for cargo so it'll remember and reuse it later?

**Comment by TheDan64** [comment]
We have a `rust-toolchain` file that cargo should be aware of. Not sure why it doesn't seem to be

**Comment by berkus** [comment]
It seems to be missing it completely; I rebuilt using manually specified toolchain and it worked; will try without manually specifying but with toolchain installed and report back.

**Comment by berkus** [comment]
```
1. rustup install nightly-2019-12-05
2. cargo install c2rust
 -- failed
3. cargo +nightly-2019-12-05 install c2rust
 -- success
```

**Comment by thedataking** [comment]
@TheDan64 the `rust-toolchain` file only comes into play when building from a git checkout AFAIK. You can `cargo install` from any directory and thus you need some other way to specify the correct toolchain.

**Comment by lu-zero** [comment]
Would be useful/interesting to update to a more current rust since had been more than half year since the snapshot?
