### ISSUE TITLE
`c2rust-bitfields-derive` not compatible with musl libc?

### ISSUE THREAD

**Issue by samuela** [immunant/c2rust#243]
Per this error (https://github.com/samuela/rustybox/issues/24#issuecomment-591315196) it sounds like c2rust-bitfields-derive doesn't work with musl libc. But the Cargo.toml doesn't have anything that seems to indicate this (https://github.com/immunant/c2rust/blob/master/c2rust-bitfields-derive/Cargo.toml). Why is cargo complaining exactly? Is there any way to get c2rust-bitfields-derive compiling on musl libc?

**Comment by rinon** [comment]
This is because of an upstream incompatibility between proc macros and static linking. See https://github.com/rust-lang/rust/issues/40174.

**Comment by kkysen** [comment]
https://github.com/rust-lang/rust/issues/40174 is now fixed.  @samuela, is this still an issue?

**Comment by kkysen** [comment]
`cd c2rust-bitfields-derive && cargo build --target x86_64-unknown-linux-musl` and `cargo build --target x86_64-unknown-linux-musl` in a test crate using `#[derive(c2rust_bitfields::BitfieldStruct)]` both worked, so I'm closing this as complete.
