### ISSUE TITLE
panicked at 'Could not find CDeclId(49711) in TypedAstContext

### ISSUE THREAD

**Issue by marce11us** [immunant/c2rust#244]
I tried to transpile efl, however it failed with

panicked at 'Could not find CDeclId(49711) in TypedAstContext

See also:
[transpile.log](https://github.com/immunant/c2rust/files/4268334/transpile.log)
The C file in question:
[evas_ector_gl_image_buffer.c.log](https://github.com/immunant/c2rust/files/4268390/evas_ector_gl_image_buffer.c.log)
included in the original C file:
[evas_ector_gl_image_buffer.eo.c.log](https://github.com/immunant/c2rust/files/4268391/evas_ector_gl_image_buffer.eo.c.log)

[compile_commands.json.log](https://github.com/immunant/c2rust/files/4268396/compile_commands.json.log)

This was done in a ubuntu 16.04 x86_64 virtual machine, with c2rust built from git with rust-nightly-2019-12-05

Tia

**Comment by thedataking** [comment]
@marce11us should be fixed in the `feature/forward_enum_decls` branch. Can you try it out and let us know if that resolves the issue for you?
