### ISSUE TITLE
Compilation of offsetof not target agnostic

### ISSUE THREAD

**Issue by pablosichert** [immunant/c2rust#248]
Hey there!

I had a bug cross-compiling to a 32-bit architecture, where the transpiled code for `offsetof` was not aware of the target architecture.

The smallest reproduction would be

```C
#include <stddef.h>

struct Foo {
    void* field1;
    void* field2;
};

typedef struct Foo Foo;

int foo() {
    return offsetof(Foo, field2);
}
```

with transpiles to

```Rust
#![allow(dead_code, mutable_transmutes, non_camel_case_types, non_snake_case,
         non_upper_case_globals, unused_assignments, unused_mut)]
#![register_tool(c2rust)]
#![feature(register_tool)]
#[no_mangle]
pub unsafe extern "C" fn foo() -> libc::c_int {
    return 8 as libc::c_ulong as libc::c_int;
}
```

The `8` here is clearly true for 64-bit pointers, but not for 32-bit.

I investigated a bit and found out that, at a first glance, the codegen for `offsetof` should be using the [`memoffset`](https://github.com/Gilnaa/memoffset) crate: https://github.com/immunant/c2rust/blob/9c018822691b7ed9e1da5df59fb75b655840f82d/c2rust-transpile/src/translator/mod.rs#L3219-L3274

But somehow, in does not seem to be the case here. I might be looking at the the wrong place?

**Comment by TheDan64** [comment]
As stated in our [faq](https://github.com/immunant/c2rust#faq), we do not currently support cross compilation at this time.

The `memoffset` crate is only used to handle a very specific edge case of offsetof which uses a non constant integer expression (non-ICE), and so your code falls under the `OffsetOfKind::Constant` arm of the code you quoted.

**Comment by pablosichert** [comment]
Would it generally be an option for you to also emit code using the `memset` crate?

I would be happy to contribute here.

Other than that it looks like this is the only part left for my code to run properly.

**Comment by pablosichert** [comment]
> We run the C preprocessor before translation to Rust. This specializes the code to the host platform.

Oh, I see. Then I'll just run it in a 32-bit Docker container for the moment.

**Comment by rinon** [comment]
I think we're open to optionally supporting code generation that uses extra crates for target agnostic output, but I'd like to at least keep the default to a minimal set of dependencies and (for the moment) target dependent.

One thing we've used to good success is the refactoring tool in C2Rust for rewriting types and function declarations into libc crate exports. However, that's not necessarily as applicable for builtin expansion like this.

**Comment by thedataking** [comment]
@pablosichert closing this issue. If you want to contribute an enhancement, feel free to reach out.
