### ISSUE TITLE
Incorrect type on converted code

### ISSUE THREAD

**Issue by xd009642** [immunant/c2rust#262]
Code generated by C2Rust 0.14.0.

So I was just trying to translate some C code from a reference implementation for a standard and found a case where the return type is clearly incorrect. 

Reference C code:

```C
typedef short Word16;
typedef long Word32;

Word16 round(Word32 L_var1) {
    Word16 var_out;
    Word32 L_arrondi;
    L_arrondi = L_add(L_var1, (Word32)0x00008000);
    var_out = extract_h(L_arrondi);
    return(var_out);
}
```

Generated Rust code

```Rust
#[no_mangle]
pub unsafe extern "C" fn round(mut L_var1: Word32) -> libc::c_double {
    let mut var_out: Word16 = 0;
    let mut L_arrondi: Word32 = 0;
    L_arrondi = L_add(L_var1, 0x8000 as libc::c_int as Word32);
    var_out = extract_h(L_arrondi);
    return var_out;
}
```

**Comment by thedataking** [comment]
Hi @xd009642, Thanks for reaching out!

The round function you are declaring has the same name as a built-in function from `<math.h>` which returns a double. If you change the function name to `my_round`, you will get the expected function signature in the translation. You can also pass the `-fno-builtin` flag when generating `compile_commands.json` to get the translation you expect. 

The C2Rust translator handles built-in functions like GCC and Clang so while perhaps confusing, what you are seeing is not a bug. If you use a modern compiler such as gcc 9, you will see a warning like this:

```
repro.c:4:8: warning: incompatible redeclaration of library function 'round' [-Wincompatible-library-redeclaration]
Word16 round(Word32 L_var1) {
       ^
repro.c:4:8: note: 'round' is a builtin with type 'double (double)'
```
