### ISSUE TITLE
Files using BitfieldStruct/#[bitfield] don't include a `use c2rust_bitfields::BitfieldStruct;`

### ISSUE THREAD

**Issue by jdm** [immunant/c2rust#265]
This ends up causing lots of errors when building until the use statement is added manually.

**Comment by ahomescu** [comment]
We never needed to do this before, having `extern crate c2rust_bitfields;` was enough. Could you provide a few more details, like what you're transpiling and what version of the Rust toolchain you're using (if you're not using our default of `2019-12-05`?

**Comment by TheDan64** [comment]
Maybe it's a 2015 edition thing?

**Comment by jdm** [comment]
I stuck all of the transpiled files together into a single Rust crate using `mod` statements, so this might be a symptom of that.

**Comment by kkysen** [comment]
This is actually a more general issue for macro calls `c2rust transpile` generates.  We shouldn't depend on external `extern crate`s and `#[macro_use]`s, and they are no longer idiomatic Rust either.  There's a new issue, https://github.com/immunant/c2rust/issues/426, to handle all of these cases, so I'm closing this issue in favor of that more general one.
