### ISSUE TITLE
Incorrect widechar string constant conversion in static variable initializer.

### ISSUE THREAD

**Issue by A1-Triard** [immunant/c2rust#267]
STR:
Transpile the following code snippet:
```c
#include <wchar.h>

struct widget_type {
        wchar_t *name;
};

struct widget_type widget_type_vbox = {
        L"vbox"
};
```

AR:
`L"vbox"` constant transpiled into nonequivalent Rust code:
```rust
[118, 0, 0, 0, 98, 0, 0, 0, 111, 0, 0, 0, 120, 0, 0, 0, 0, 0, 0, 0].as_ptr() as *mut wchar_t
```

ER:
`L"vbox"` constant should be transpiled to something like
```rust
[118, 98, 111, 120, 0].as_ptr() as *mut _
```

**Comment by thedataking** [comment]
@A1-Triard thanks for bringing this issue to our attention. I pushed a fix to a new branch `feature/issue267` – feel free to try it out and let me know if it resolves your issue. Once all the CI checks pass, we'll merge the fix into `master` via PR #268.

**Comment by A1-Triard** [comment]
> feel free to try it out and let me know if it resolves your issue.

Yes, it does, but there is now another small issue in generated code:

> `std::intrinsics::transmute` is not yet stable as a const fn
> help: add `#![feature(const_transmute)]` to the crate attributes to enable

**Comment by thedataking** [comment]
Ah, thanks for the catch. It should be fixed now.
