### ISSUE TITLE
"Couldn't strip common ancestor path" when running on single translation unit

### ISSUE THREAD

**Issue by panstromek** [immunant/c2rust#271]
When I run the tool on just a single file (it's unity build, all other files are included into it and `compile_commands.json` has only single entry), I get panic with "Couldn't strip common ancestor path".

I looked through the source code and I found that this `expect` panics https://github.com/immunant/c2rust/blob/fbd5c0a96c6eb6a3c5913ca7a06e5d35d3cea072/c2rust-transpile/src/lib.rs#L557

Seems like it's probably because common ancestor path is empty when there are no other paths?

If I add another empty file to the project, transpilation runs fine.

**Comment by ahomescu** [comment]
What's the path in `compile_commands.json` to that single file? The path in `ancestor_path` is computed using `abs_file` which returns a canonicalized absolute path, so the problem could be that in `path_buf.strip_prefix(ancestor_path)` the `path_buf` path is relative but `ancestor_path` is absolute.

**Comment by panstromek** [comment]
it's this:
```json
        "directory": "/home/panstromek/zebra-1",
        "file": "unity.c"
```

**Comment by thedataking** [comment]
Hi @panstromek,

I checked out zebra-1 and built it on my machine using `bear` to `generate compile_commmands.json`. I didn't find a way to do a unity build like you described, so I simply edited my `compile_commands.json` to only contain:

```json
[
    {
        "arguments": [
            "gcc",
            "-c",
            "-O4",
            "-fomit-frame-pointer",
            "-falign-functions=32",
            "-Wall",
            "-Wcast-align",
            "-Wwrite-strings",
            "-Wstrict-prototypes",
            "-Winline",
            "-DINCLUDE_BOOKTOOL",
            "-DTEXT_BASED",
            "-DZLIB_STATIC",
            "-o",
            "bitbtest.o",
            "bitbtest.c"
        ],
        "directory": "/home/perl/zebra-1",
        "file": "bitbtest.c"
    }
]
```

Which works just fine with the latest c2rust built from `master` on Ubuntu 20.04. Here's how I transpile:

    PATH=$HOME/Work/c2rust/target/release:$PATH c2rust transpile compile_commands.json

Maybe you can attach your compile commands to help us reproduce the issue? Do you pass additional translator options?

**Comment by panstromek** [comment]
Wow, I'm impressed you took the extra effort to find that repo and build it, I didn't even realize I have a public fork 😉 I thought it'll be more straightforward to reproduce, sorry for that. I made the unity build just because the regular transpiled version failed to link, but it's not needed to reproduce it (I'll ask about the linking on discord when I get back to this).

Anyway, the simplest reproduction I found seems to be

```c
// bitbtest.c
int main () {}
```

```json
 //compile-commands.json
[
    {
        "arguments": [
            "gcc",
            "-c",
            "-O4",
            "-fomit-frame-pointer",
            "-falign-functions=32",
            "-Wall",
            "-Wcast-align",
            "-Wwrite-strings",
            "-Wstrict-prototypes",
            "-Winline",
            "-DINCLUDE_BOOKTOOL",
            "-DTEXT_BASED",
            "-DZLIB_STATIC",
            "-o",
            "bitbtest.o",
            "bitbtest.c"
        ],
        "directory": "/home/panstromek/zebra-1",
        "file": "bitbtest.c"
    }
]
```
and run
```bash
c2rust transpile ./compile_commands.json -o ./
```

I am running c2rust with `-o ./`. I forgot to mention that before (I didn' realize it's important, but it seems it doesn't actually reproduce without it.

**Comment by thedataking** [comment]
@panstromek thanks for helping me reproduce. Should be fixed now; let me know if you still get an error.
