### ISSUE TITLE
Workaround needed for running c2rust on Centos 8 using LLVM 9

### ISSUE THREAD

**Issue by vectorphresh** [immunant/c2rust#299]
I am seeing the following error after compiling and running c2rust:

```
: CommandLine Error: Option 'limited-coverage-experimental' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```
There are two bugs written against LLVM that provide some insight on the issue, which I think is related to statically linking c2rust to the LLVM libraries:
https://bugs.llvm.org/show_bug.cgi?id=22952
https://bugs.llvm.org/show_bug.cgi?id=30587

I am looking for a work around to allow c2rust to be built without statically linking to the LLVM libraries. I am not as familiar enough with LLVM and would like assistance in finding a solution.

Thanks you.

**Comment by fw-immunant** [comment]
This seems like a distro problem, and CentOS 8 reached EOL at the end of 2021. It's probably easier to try installing it on Ubuntu or Debian. We could try to support dynamically linking to LLVM libs for its own sake, but I don't think this issue is best solved on the c2rust side.
