### ISSUE TITLE
Failed to compile...

### ISSUE THREAD

**Issue by ergpopler** [immunant/c2rust#316]
[ 75%] Building CXX object CMakeFiles/clangAstExporter.dir/AstExporter.cpp.o

--- stderr
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_ASM_COMPILER
    CMAKE_ASM_FLAGS

/home/theo/.cargo/registry/src/github.com-1ecc6299db9ec823/c2rust-ast-exporter-0.15.0/src/AstExporter.cpp:15:10: fatal error: clang/Frontend/FrontendActions.h: No such file or directory
   15 | #include "clang/Frontend/FrontendActions.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[3]: *** [CMakeFiles/clangAstExporter.dir/build.make:82: CMakeFiles/clangAstExporter.dir/AstExporter.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:102: CMakeFiles/clangAstExporter.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:109: CMakeFiles/clangAstExporter.dir/rule] Error 2
gmake: *** [Makefile:137: clangAstExporter] Error 2
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2

build script failed, must exit now', /home/theo/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.45/src/lib.rs:894:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile `c2rust v0.15.1`, intermediate artifacts can be found at `/tmp/cargo-installRC8z9M`

platform: OpenSUSE Tumbleweed.

**Comment by thedataking** [comment]
Looks like you don't have the clang headers installed (or they are not picked up during makefile generation). On Ubuntu, you'd need to install the libclang-dev, I'm not sure what the corresponding OpenSUSE package is called but that's where I'd start.

**Comment by ergpopler** [comment]
I have "libclang10" & "libclang11" which would be the equiv. Still, the issue persists.

**Comment by ergpopler** [comment]
Actually, I got that part to work, clang11-devel i believe.. 
now I am getting this issue though, 
`[ 91%] Building CXX object CMakeFiles/clangAstExporter.dir/ExportResult.cpp.o

--- stderr
/home/theo/Makes/c2rust/c2rust-ast-exporter/src/AstExporter.cpp: In lambda function:
/home/theo/Makes/c2rust/c2rust-ast-exporter/src/AstExporter.cpp:2466:37: error: ‘class clang::ASTContext’ has no member named ‘getRawCommentList’; did you mean ‘DeclRawComments’?
 2466 |             auto comments = Context.getRawCommentList().getCommentsInFile(file);
      |                                     ^~~~~~~~~~~~~~~~~
      |                                     DeclRawComments
/home/theo/Makes/c2rust/c2rust-ast-exporter/src/AstExporter.cpp: In function ‘std::vector<const char*, std::allocator<const char*> > augment_argv(int, const char**)’:
/home/theo/Makes/c2rust/c2rust-ast-exporter/src/AstExporter.cpp:2565:37: error: conversion from ‘llvm::StringRef’ to non-scalar type ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’} requested
 2565 |     std::string resource_dir = P.str();
      |                                ~~~~~^~
gmake[3]: *** [CMakeFiles/clangAstExporter.dir/build.make:82: CMakeFiles/clangAstExporter.dir/AstExporter.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:103: CMakeFiles/clangAstExporter.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/clangAstExporter.dir/rule] Error 2
gmake: *** [Makefile:137: clangAstExporter] Error 2
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2

build script failed, must exit now', /home/theo/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.42/src/lib.rs:861:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.`

**Comment by thedataking** [comment]
yeah, since OpenSUSE is rpm based, you'll need clang-devel. It will work if you use the packages based on clang/LLVM 10.

Here's a Dockerfile that shows how to build on OpenSUSE:
```
FROM opensuse/tumbleweed

RUN zypper install -y \
    curl \
    cmake \
    gcc \
    gcc-c++ \
    git \
    clang10-devel \
    libopenssl-devel
    
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly-2019-12-05

RUN git clone https://github.com/immunant/c2rust.git

WORKDIR c2rust

RUN source $HOME/.cargo/env && cargo build
```

**Comment by paulyoung** [comment]
I'm running into this exact error on macOS using the `shell.nix` file provided in the repo.

**Comment by jaredforrest** [comment]
@paulyoung If you're still having this issue I managed to fix it by adding pkgs.libclang to buildInputs and changing   LIBCLANG_PATH="${llvmPackages.libclang}/lib"; to LIBCLANG_PATH="${llvmPackages.libclang.lib}/lib";
