### ISSUE TITLE
c2rust is frustrating to build, and there are no prepared docker images

### ISSUE THREAD

**Issue by xorgy** [immunant/c2rust#319]
I've tried building c2rust with the instructions in the readme, and also tried building the dockerfile, and also tried cargo install with both a current nightly and the specified old nightly toolchain, and none of them built. I used to be able to build c2rust on ArchLinux pretty easily. I managed to figure it out eventually, but it seems like there are a number of things making it a mess.

I presume from the old nightly toolchain choice that the way rustc is compiled broke with later toolchains, is there no interest in addressing this upstream?

Since I mainly just wanted to run the c2rust tools once or twice, I thought at least I could find a docker image, or the dockerfile would build successfully, but neither appears to be the case so I would otherwise have been out of luck.

**Comment by xorgy** [comment]
Going to try with the outstanding LLVM 11 branch, because I think one of the ways I tried to build c2rust failed when compiling against clang.

**Comment by ahomescu** [comment]
On my Arch machine (updated today) with LLVM&clang 11 and on latest C2Rust `master`, `cargo build --release` works just fine. Did you try that? The C2Rust binaries from `target/release` should be perfectly usable.

**Comment by thedataking** [comment]
Hi @xorgy, although we do not link to them, you can find premade images that we use for CI here: 

https://hub.docker.com/r/immunant/c2rust/tags

If you pull c2rust master and build in one of these, it should succeed. You can also use `path/to/scripts/docker_build.sh archlinux/base` to build the archlinux docker image locally if you prefer. Hope one of these options gets you up and running.
