### ISSUE TITLE
about the docker container you provide

### ISSUE THREAD

**Issue by cleanyong** [immunant/c2rust#33]
Hi Immunant,

I am very interested to convert C to Rust.

I followed instructions and can run docker just fine. I plan to transpile some C project outside your docker container but failed to share host file system with docker container. Did you build the docker image without the sudo access? I want a way to transpile the project on host file system, or need a way to move the project on to the docker container.

Please advise, thanks.

Clean Yong

**Comment by thedataking** [comment]
Hi @cleanyong, 

If you haven't already, take a look at `docker_run.sh` which sets up the mappings between the host file system and the docker container. By default, $C2RUST_HOME is shared with the docker container but you can easily share additional folders by modifying the script.

If you need to perform privileged operations inside the container, try passing the `--privileged` flags to the `docker run` command. 

Hope this helps!

**Comment by cleanyong** [comment]
Are there any way to upgrade the docker cmake version to 3.12, right now is 3.10.2.

I got this error message:

``` shell
docker@docker:~/C2Rust$ ./scripts/transpile.py -e /mnt/build/compile_commands.json
exporting ast from KeccakHash.c
 importing ast from KeccakHash.c.cbor
exporting ast from KeccakP-1600-AVX2.cpp
 importing ast from KeccakP-1600-AVX2.cpp.cbor
Traceback (most recent call last):
  File "./scripts/transpile.py", line 490, in <module>
    main()
  File "./scripts/transpile.py", line 484, in main
    reorganize_definitions=args.reorganize_definitions)
  File "./scripts/transpile.py", line 365, in transpile_files
    results = [transpile_single(cmd) for cmd in commands]
  File "./scripts/transpile.py", line 365, in <listcomp>
    results = [transpile_single(cmd) for cmd in commands]
  File "./scripts/transpile.py", line 350, in transpile_single
    assert cbor_file.endswith(".c.cbor"), e
AssertionError: Expected file suffix `.c.cbor`; actual: KeccakP-1600-AVX2.cpp.cbor
docker@docker:~/C2Rust$
```

**Comment by boomshroom** [comment]
I already took the time to build the transpiler. Do I need to delete the container and regenerate it in order to mount the directory? It would be nice if I could move the mount to switch projects without recompiling everything.

**Comment by thedataking** [comment]
@cleanyong we recently moved away from the `transpile.py` script so that should also avoid the assertion you are hitting. Mind giving it another try and letting me know?

@boomshroom not sure I follow your question. Can  you provide more detail if still unresolved?

**Comment by boomshroom** [comment]
The transition from python to rust definitely made it easier. As for my problem, I was able to get around it by just moving the source I wanted translated into C2Rust's folder.

**Comment by thedataking** [comment]
Closing this issue. Feel free to reopen or open new issues if anything else comes up.
