### ISSUE TITLE
Use va_list-rs crate or core::ffi::VaList

### ISSUE THREAD

**Issue by dlrobertson** [immunant/c2rust#34]
I noticed C2rust has some support for `va_list` and seems to manually create the correct structure. If c2rust is expected to generate Rust for nightly channels you should be able to use `core::ffi::VaList` (**NB**: I've only really tested x86 and x86_64). If nightly is not an option and/or if more stability is desired, the [va_list-rs] crate works well.

[va_list-rs]: https://github.com/thepowersgang/va_list-rs

**Comment by glguy** [comment]
The internal version of c2rust is using the nightly `core::ffi::VaList`. We're hoping to push the changes out very soon!

**Comment by dlrobertson** [comment]
:+1: Awesome!
