### ISSUE TITLE
`c2rust-refactor` depends on `librustc_driver` outside linker path

### ISSUE THREAD

**Issue by chrysn** [immunant/c2rust#349]
When c2rust is built as

    $ cargo install --locked --root /usr --path ./c2rust

then the installed c2rust-refactor tool is not generally usable:

    $ c2rust-refactor 
    c2rust-refactor: error while loading shared libraries: librustc_driver-0f85f1014fece72d.so: cannot open shared object file: No such file or directory

It can still be executed by reaching into the build toolchain's support files for as long as they are available:

    $ LD_LIBRARY_PATH=~/.rustup/toolchains/nightly-2019-12-05-x86_64-unknown-linux-gnu/lib/ c2rust-refactor
    error: The following required arguments were not provided:
    ...

I don't understand the build system well enough to make an informed recommendation (neither do I use the refactor tool, so it's more of a curious observation from exploring #326); posting here in case anyone has a quick idea, and otherwise just to document the workaround.

**Comment by kkysen** [comment]
Closing as `c2rust-refactor` in its current form is no longer being developed.
