### ISSUE TITLE
Can't locate lib file

### ISSUE THREAD

**Issue by prat-agarwal** [immunant/c2rust#361]
It's not able to find `libclangToolingInclusions.a`
I tried 'locate libclangToolingInclusions.a` but got no results

`[name]@[name] ~/Rust/c2rust (master) $cargo build --release
   Compiling c2rust-ast-exporter v0.15.0 (/home/[name]/Rust/c2rust/c2rust-ast-exporter)
   Compiling c2rust-refactor v0.15.0 (/home/[name]/Rust/c2rust/c2rust-refactor)
error: failed to run custom build command for `c2rust-ast-exporter v0.15.0 (/home/[name]/Rust/c2rust/c2rust-ast-exporter)`

Caused by:
  process didn't exit successfully: `/home/[name]/Rust/c2rust/target/release/build/c2rust-ast-exporter-f3875322a333f2a5/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "cmake" "/home/[name]/Rust/c2rust/c2rust-ast-exporter/src" "-DLLVM_DIR=/usr/lib/llvm-3.8/lib/cmake/llvm" "-DClang_DIR=/usr/lib/llvm-3.8/lib/cmake/clang" "-DCMAKE_INSTALL_PREFIX=/home/[name]/Rust/c2rust/target/release/build/c2rust-ast-exporter-91a18e0a0e708260/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Release"
-- Configuring incomplete, errors occurred!
See also "/home/[name]/Rust/c2rust/target/release/build/c2rust-ast-exporter-91a18e0a0e708260/out/build/CMakeFiles/CMakeOutput.log".

--- stderr
CMake Error at /usr/lib64/cmake/clang/ClangTargets.cmake:535 (message):
  The imported target "clangToolingInclusions" references the file

     "/usr/lib64/libclangToolingInclusions.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib64/cmake/clang/ClangTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib/cmake/clang/ClangConfig.cmake:18 (include)
  CMakeLists.txt:47 (find_package)

thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', /home/[name]/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.42/src/lib.rs:861:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
^C  Building [=====================================================> ] 369/375: c2rust-refactor`

`[name]@[name] ~/Rust/c2rust (master) $rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/[name]/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-2019-12-05-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
1.14-x86_64-unknown-linux-gnu
1.41-x86_64-unknown-linux-gnu
1.44-x86_64-unknown-linux-gnu
1.51-x86_64-unknown-linux-gnu (default)
1.44.0-x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-2019-12-05-x86_64-unknown-linux-gnu (overridden by '/home/[name]/Rust/c2rust/rust-toolchain')
rustc 1.41.0-nightly (6d77e45f0 2019-12-04)`

**Comment by thedataking** [comment]
Can you share what distro you are on? It looks like you do not have the clang or LLVM development package installed or discoverable on your host. You can see how we provision the necessary packages for CI by looking at the scripts folder.

**Comment by prat-agarwal** [comment]
I upgraded to this system and it installed flawlessly. Thanks.


Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
