### ISSUE TITLE
Transpile llvm_asm to asm

### ISSUE THREAD

**Issue by chrysn** [immunant/c2rust#363]
With the stabilization of the new asm language, the old llvm_asm is getting deprecated in Rust, creating the threat of eventual removal.

To build stable Rust code, we should aim to not just copy over the (LLVM / GCC style) assembly from C code, but try to change it to the newer (and stable) assembly language.

(#306 is different from this; that is just about emitting the old assembly with the new llvm_asm names).

I'm aware this is not a trivial request; it may be necessary to look for use cases that sponsor work on this.

---

Possible alternatives:

* It may be possible to create extra assembly files for the blocks and then pull them in from the generated Rust code. It may also not.
* Persuade Rust maintainers to keep llvm permanently deprecated -- discussion in https://github.com/rust-lang/rust/issues/70173 is not clear yet: deprecation happened and removal is announced, without any actual timeline for removal (or even a certainty that it will be removed)
* Deprecate support for ASM in transpiled C.

**Comment by Amanieu** [comment]
`llvm_asm!` is being removed in https://github.com/rust-lang/rust/pull/92816.

**Comment by chrysn** [comment]
This is going to be very painful; I had hoped we'd have a bit of time.

Do you see any chance of implementing asm generation within the time
frame of llvm_asm's removal?

**Comment by Amanieu** [comment]
From what I can tell the assembly currently produced by c2rust doesn't even work on the latest nightly (or in fact any nightly in the last 2 years) since it's using the old LLVM assembly syntax with `asm!`.

**Comment by fw-immunant** [comment]
`llvm_asm` was recently [removed](https://github.com/rust-lang/rust/pull/92816), which makes this a bit more urgent as a requirement for supporting current rustc.

**Comment by fw-immunant** [comment]
I've done a (fairly unpolished, and assuming x86_64 in a few places) pass at this in the [syn PR](https://github.com/immunant/c2rust/pull/374), because it's a necessary part of bringing us up to speed with the rest of the Rust ecosystem. Test coverage is still lacking, so any feedback would be particularly appreciated.

**Comment by fw-immunant** [comment]
#374 has merged, but I'll leave this bug open until we have broader test coverage to better validate the asm translation. Currently there's some minimal asm for a bswap implementation that gets dragged in from system headers, a few places doing cpuid, and a few mathy bits from python in the testsuite, but we would do well to have targeted test cases for inline asm in the c2rust repo itself.
