### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by zamazan4ik** [immunant/c2rust#365]
Hi!

Are there any plans to publish a new release? As far as I see, there are a lot of changes, which can be delivered to end-users with a new release.

Thanks in advance!

**Comment by rinon** [comment]
Yes, there is! We're working on decoupling the transpiler from Rust nightly. When that is finished we'll bundle up a release. This should make usage a lot simpler, as you won't need to build with an ancient toolchain. Thanks for the suggestion, I'll keep this issue open until the new version is ready.

**Comment by chrysn** [comment]
Thanks a lot, you're awesome. `cargo install c2rust` is something I wouldn't have hoped for half a year ago.
