### ISSUE TITLE
Linux Kernel Support

### ISSUE THREAD

**Issue by leongross** [immunant/c2rust#370]
Are there plans to provide support for linux kernel headers / support for using Kbuild architecture?
This could be especially interesting considering the efforts of introducing Rust into the [Linux Kernel](https://github.com/Rust-for-Linux/).

**Comment by fw-immunant** [comment]
There are no plans to do this--as far as I'm aware the Rust for Linux project is only interested in manually porting drivers for now, and trying to find Rust expressions of higher-level patterns than the individual operation-by-operation translation that c2rust does. We certainly applaud their efforts but I don't think there's much overlap.

Regarding Kbuild support, c2rust is generally intended for the use-case of translating a project built with any C build system to a project built with Cargo, and the only requirement for build-system compatibility is the ability to generate a `compile_commands.json` file. Kbuild itself, if I'm not mistaken, is more oriented toward significant compile-time configuration in a way that c2rust does not interpret. A Kbuild-to-cargo-and-build.rs translator might be interesting, but is outside the scope of c2rust as currently envisioned.
