### ISSUE TITLE
linking with `cc` failed: libclangTooling.a: error adding symbols: File format not recognized

### ISSUE THREAD

**Issue by Des-Nerger** [immunant/c2rust#376]
[c2rust_build.log](https://github.com/immunant/c2rust/files/8469599/c2rust_build.log)

**Comment by fw-immunant** [comment]
I don't think there's enough information here to diagnose this build failure from our side. It looks like something is (from the perspective of the linker) wrong with your installation of LLVM 7. What OS/distro are you running, and what linker are you using? Where did you get this LLVM (package manager from which distro/release, custom built from which sources, binaries from releases.llvm.org)?

**Comment by Des-Nerger** [comment]
> What OS/distro are you running, and what linker are you using?

Ubuntu 14.04 (Trusty), and my `/usr/bin/ld` comes from GNU binutils=2.28-3ubuntu1~14.04.york0

> Where did you get this LLVM (package manager from which distro/release, custom built from which sources, binaries from releases.llvm.org)?
```
$ apt-cache policy llvm-7
llvm-7:
  Installed: 1:7.1.0~svn353565-1~exp1~20190419134007.64
  Candidate: 1:7.1.0~svn353565-1~exp1~20190419134007.64
  Version table:
 *** 1:7.1.0~svn353565-1~exp1~20190419134007.64 0
        500 http://apt.llvm.org/trusty/ llvm-toolchain-trusty-7/main amd64 Packages
```

**Comment by Des-Nerger** [comment]
Thanks for the clue about the incompatibility. I didn't need to install/update any software, though.
I was able to build c2rust successfully by symlinking already installed lld: `$ sudo ln -s /usr/bin/ld.lld-7 /usr/bin/ld.lld` and then adding `RUSTFLAGS="-C link-arg=-fuse-ld=lld"` to the cargo build command.

**Comment by Des-Nerger** [comment]
Today I tried to rebuild `c2rust` on the newest Debian Testing, having binutils=v2.41 llvm=v16.0.6 and got a similar linking error, which I easily fixed just passing `RUSTFLAGS="-C link-arg=-fuse-ld=lld"` to `cargo build`.

I think you should be explicit about the `c2rust`'s hard reliance on `lld`, perhaps modifying default `rustflags` similar to what the Bevy game engine does for its "fast builds": https://github.com/bevyengine/bevy/blob/main/.cargo/config_fast_builds

**Comment by thedataking** [comment]
> I think you should be explicit about the c2rust's hard reliance on lld

This is the first time I hear about having to use `ldd` to build c2rust. I'm glad you got it to work (and thanks for sharing your workaround). On all the platforms we regular, it is not necessary to use `ldd` AFAIK.

**Comment by Des-Nerger** [comment]
Hm, that's weird.
Here's the full log without the `lld` "workaround", if you're interested: 
[c2rust_issues_376_cargo_build_release_verbose.log](https://github.com/immunant/c2rust/files/13513509/c2rust_issues_376_cargo_build_release_verbose.log)
