### ISSUE TITLE
Git version, release

### ISSUE THREAD

**Issue by chrysn** [immunant/c2rust#388]
There's been a lot of change in C2Rust (for the better, thanks for that!), and the version in c2rust/Cargo.toml is still at 0.15.1.

Please consider reporting the git commit in `--version` if available, and/or setting the version to `0.16.0-git` between releases. That'd help a lot when debugging whether something is a C2Rust or downstream issue. ("Which version of c2rust are you using?" is a bit hard to answer for those who run into an issue the first time).

Speaking of releases, would you consider uploading a version to cargo at some point in time again? Now that it works on regular Rust releases, that'd open up for plain `cargo install c2rust`.

**Comment by fw-immunant** [comment]
I've asked @rinon to bake a release after the following outstanding PRs have been merged:
- [ ] #375
- [ ] #383 
- [ ] #385 
- [ ] #386

**Comment by fw-immunant** [comment]
The release itself is tracked in #365.
