### ISSUE TITLE
Update to clap3

### ISSUE THREAD

**Issue by rinon** [immunant/c2rust#395]
Clap3 deprecated YAML support, so we need to rewrite command-line parsing to use the new APIs.

**Comment by kkysen** [comment]
Did `clap` 3 actually deprecate yaml support?  #702 suggests it didn't, and from `clap`'s documentation (v3 and v4) it seems like yaml is still supported.  If that's the case, then we can just upgrade `clap` to 3 and even 4 without changes.  I think using the derive API is a lot cleaner and type-safe, but that can be done separately from updating the `clap` dependency.

**Comment by rinon** [comment]
deprecated != removed (https://github.com/clap-rs/clap/issues/3087). This is very low priority though.

**Comment by kkysen** [comment]
Ah, okay.  I missed that.  Though can't we still upgrade to `clap` 3, though, so we only have one `clap` version and faster builds.  Then leave this issue for moving away from the yaml API?  I get that it's not very important, though, but #702 was trying to do it but without removing the yaml.

**Comment by marcograss** [comment]
#703 now

**Comment by fw-immunant** [comment]
Fixed by #703.

**Comment by kkysen** [comment]
Not really fixed by #703.  Actually will be fixed by #777, so we'll close this when that merges.
