### ISSUE TITLE
Provide binaries

### ISSUE THREAD

**Issue by thedrow** [immunant/c2rust#4]
Since compiling c2rust takes a while it'd be nice if the CI process could provide binaries when creating a tag in this repository.

**Comment by chocol4te** [comment]
I can start work on Travis builds for the releases tab tomorrow :)

**Comment by harpocrates** [comment]
This is definitely something on the roadmap. Right now, there are two completely separate programs: a Clang plugin `ast-extractor` (which exports the type-annotated C AST) and a Cargo managed `ast-importer` (which does the the actual translation).

It would be nice to combine these into a single binary before before providing prebuilt binaries.

**Comment by thedataking** [comment]
Closing since it is now possible to `cargo install` from crates.io. See instructions [here](https://github.com/immunant/c2rust#installing-from-cratesio).

**Comment by theoparis** [comment]
The crates.io release seems very out of date  and fails to compile.  Also, it'd be nice to not have to install specific clang and rustc nightly versions to obtain the latest c2rust...  maybe there can be prebuilt binaries with statically linked libclang?
```
error: attributes starting with `rustc` are reserved for use by the `rustc` compiler
  --> /home/theo/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-0.37.25/src/backend/linux_raw/io/errno.rs:28:25
   |
28 | #[cfg_attr(rustc_attrs, rustc_layout_scalar_valid_range_start(0xf001))]
   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

```
          mold: error: undefined symbol: llvm::Error::fatalUncheckedError() const
          >>> referenced by AstExporter.cpp
          >>>               /home/theo/src/c2rust/target/release/build/c2rust/74264c3b81f23455/out/rustcHCrl2o/libc2rust_ast_exporter-8f28bdbce60601a6.rlib(AstExporter.cpp.o):(process(int, char const**, int*, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >*) [clone .cold])
          >>> referenced by AstExporter.cpp
```
