### ISSUE TITLE
Broken link in c2rust-refactor/README.md

### ISSUE THREAD

**Issue by d33tah** [immunant/c2rust#41]
The file points to the dead link:

https://github.com/immunant/c2rust/blob/master/c2rust-refactor/commands.html

**Comment by rinon** [comment]
Unfortunately that link points to an autogenerated file that is built as part of the manual. I don't really have a great solution, because I don't want to hardcode a link to the online manual: https://c2rust.com/manual/c2rust-refactor/commands.html

**Comment by samuela** [comment]
I just ran into the same issue, and it's quite confusing. The link is also broken on the official docs page AFAICT: https://docs.rs/crate/c2rust-refactor/0.13.0.

**Comment by jeffvandyke** [comment]
Just noticed it myself too, starting to get more into this project. Just as it seems common practice to link to a project homepage, if the link is relatively stable, I think a link to the online manual would be fine in this case, maybe labeled with something like "the command documentation (online)" or (c2rust.com), something like that, at least while that is considered a stable resting place for those command docs.

(BTW, the "select" command link is also broken)
