### ISSUE TITLE
Update `bindgen` dependency

### ISSUE THREAD

**Issue by kkysen** [immunant/c2rust#425]
`bindgen` currently generates layout tests that invoke UB, specifically nullptr derefs (see https://github.com/rust-lang/rust-bindgen/issues/1651).  These are warned by `rustc` and may be errors soon.  A fix (https://github.com/rust-lang/rust-bindgen/pull/2203 on 5/17/2022) has already been merged, but hasn't landed in a release yet.  So we should update our `bindgen` dependencies as soon as a new release lands.

**Comment by fw-immunant** [comment]
[Bindgen 0.60.1 just came out](https://github.com/rust-lang/rust-bindgen/commit/9ca5f856a35deddde0575002d76d1db4430e6c42); I'll bump our dep prior to our pending 0.16.1 release.

**Comment by kkysen** [comment]
Great!  I just checked; 0.60 fixes the issue.
