### ISSUE TITLE
feature request: <stdint.h> types to Rust's builtin primitives?

### ISSUE THREAD

**Issue by KisaragiEffective** [immunant/c2rust#432]
In C99 (or later), a header named `stdint.h` provides `/^u?int(?:8|16|32|64)_t$/` type aliases (displayed in regex) if the compilation platform supports those integer types natively. (I think most platform we often use support them)
They have exact bit width, so I think they should correspond with `^[ui](?:8|16|32|64)$` respectively.
If it was enabled, the code would be more readable.

**Comment by fw-immunant** [comment]
This is indeed something we should do, and is already tracked in issue #259.
