### ISSUE TITLE
`c2rust instrument` should apply extra `cargo` args

### ISSUE THREAD

**Issue by kkysen** [immunant/c2rust#448]
Currently, `c2rust instrument` takes extra `cargo` args to apply when instrumenting a crate it's building.  However, in `c2rust_dynamic_instrumentation::instrument`, these args are unused, and the compilation is a default `cargo` debug build.  For example, if you try to do a release build with `--release`, you can't.  Running the instrumented binary in release mode seems like a fairly important thing to be able to do for performance reasons.  The issue goes a lot deeper than just not using these extra arguments, however.

In `c2rust_dynamic_instrumentation`, we use the [`cargo`](https://docs.rs/cargo/) crate and its APIs directly.  There are APIs for replicating the passed `cargo` args, such as [`BuildConfig::requested_profile`](https://docs.rs/cargo/latest/cargo/core/compiler/struct.BuildConfig.html#structfield.requested_profile).  However, all of `cargo`'s logic for parsing the args, applying them, and creating a [`CompileOptions`](https://docs.rs/cargo/latest/cargo/ops/struct.CompileOptions.html) are in [`src/bin/cargo/`](https://github.com/rust-lang/cargo/tree/master/src/bin/cargo).  That is, they are within `cargo`'s binary crates, and as such, are private, so we cannot use them at all.  So if we want to support extra `cargo` args in the same way `cargo` handles them, we would have to duplicate `cargo`'s arg parsing code, and we would have to always keep it in sync with changes to `cargo`.  This seems quite brittle.

There is a public [`cargo::util::command_prelude::ArgMatchesExt`](https://docs.rs/cargo/latest/cargo/util/command_prelude/trait.ArgMatchesExt.html) that contains a significant portion of the logic for parsing a [`clap::ArgMatches`](https://docs.rs/clap/latest/clap/struct.ArgMatches.html) into [`CompileOptions`](https://docs.rs/cargo/latest/cargo/ops/struct.CompileOptions.html).  However, the [`clap::ArgMatches`](https://docs.rs/clap/latest/clap/struct.ArgMatches.html) is generated from a [`clap::App`](https://docs.rs/clap/latest/clap/struct.App.html) from [`src/bin/cargo/`](https://github.com/rust-lang/cargo/tree/master/src/bin/cargo), once again private.  So we could duplicate less code, but still have to duplicate the [`clap::App`](https://docs.rs/clap/latest/clap/struct.App.html)-building code and the code that uses [`cargo::util::command_prelude::ArgMatchesExt`](https://docs.rs/cargo/latest/cargo/util/command_prelude/trait.ArgMatchesExt.html).

As an alternative, I looked at other crates that are doing very similar things with `rustc` internals as we are: [`clippy`](https://github.com/rust-lang/rust-clippy/) and [`miri`](https://github.com/rust-lang/miri).  They both use rustc internals like [`rustc_driver::RunCompiler`](https://doc.rust-lang.org/stable/nightly-rustc/rustc_driver/struct.RunCompiler.html) and [`impl rustc_driver::Callbacks`](https://doc.rust-lang.org/stable/nightly-rustc/rustc_driver/trait.Callbacks.html), just like we do.  However, neither of them use the [`cargo`](https://docs.rs/cargo/) crate and its APIs directly.  And of [the crates that do depend](https://crates.io/crates/cargo/reverse_dependencies) on [`cargo`](https://docs.rs/cargo/), they all seem to either not touch `rustc_driver` and other `rustc` internals or re-implement a small subset of the the `cargo` args API in a slightly different way from `cargo`.

Instead, [`clippy`](https://github.com/rust-lang/rust-clippy/blob/master/src/main.rs) and [`miri`](https://github.com/rust-lang/miri/blob/master/src/bin/miri.rs) both invoke `cargo` as a subcommand, override `$RUSTC_WRAPPER` to [`clippy-driver`](https://github.com/rust-lang/rust-clippy/blob/master/src/driver.rs) and [`miri`](https://github.com/rust-lang/miri/blob/master/src/bin/miri.rs), and it is within `clippy-driver` and `miri` that it has [`impl rustc_driver::Callbacks`](https://doc.rust-lang.org/stable/nightly-rustc/rustc_driver/trait.Callbacks.html) and uses [`rustc_driver::RunCompiler`](https://doc.rust-lang.org/stable/nightly-rustc/rustc_driver/struct.RunCompiler.html).

I think it would be better to re-architect `c2rust_dynamic_instrumentation`.  Instead of using the [`compile_with_exec`](https://docs.rs/cargo/latest/cargo/ops/fn.compile_with_exec.html) API, we should:
* take the approach of `clippy` and `miri`
* drop the dependency on `cargo` unless it is needed for unrelated things
* invoke `cargo` as a subcommand
* pass the extra `cargo` args to the `cargo` subcommand, which will do its proper argument parsing
* set `RUSTC_WRAPPER=c2rust-instrument`
* and then use `rustc_driver` when invoked as `rustc`

This also has a few added benefits:
* We will be able to run `cargo c2rust-instrument` with this architecture.
* We explicitly set `$RUSTC_WRAPPER` to ourselves, which avoids crashes when `$RUSTC_WRAPPER` is set to something else, such as `RUSTC_WRAPPER=sccache`, which may be set globally.  The error messages from this crash do not point to `$RUSTC_WRAPPER` being the culprit at all, so it would be good to fix this bug, too.  At the very least, we should clear `$RUSTC_WRAPPER` so this bug doesn't happen.
* We're following the much more widely-used and proven architectures of `clippy` and `miri`.

This might not be the most urgent thing to fix, but I do think it should come before optimizations to the instrumentation, such as de-duplicating it on the fly.  Being able to run it in release mode first seems like a better first approach to performance issues.

**Comment by fw-immunant** [comment]
I like this idea. I think the current driver setup was mostly put together by @rinon<span></span>--thoughts?

**Comment by kkysen** [comment]
If we drop the `cargo` dependency, we also can drop the `openssl` dependency, which is an odd dependency for what `c2rust` is doing.

**Comment by rinon** [comment]
hmmmm that's some good detective work @kkysen. I didn't actually think about what clippy does, but instead I was replicating what we did for the refactoring engine. We'll want some way to specify which crate we want to instrument, as we don't want to instrument all dependencies, but we can probably figure out something there. Maybe an extra environment variable if we have to?

Yeah, I agree, making cargo drive things seems much more reasonable in this case.

**Comment by kkysen** [comment]
Yeah, I think an environment variable to pass some extra info would work well.  `clippy` and `miri` do that, too.

Which crates do we instrument?  Just the root, transpiled one, and not (Rust) dependencies?

**Comment by rinon** [comment]
Right now we just instrument the root crate, not the dependencies. We especially need to be careful that we don't instrument the runtime, or we'll get fun issues with circular dependencies.

**Comment by kkysen** [comment]
We will get a `$RUSTC_WRAPPER rustc --crate-name $crate_name` command, so we might be able to just check that, right?

**Comment by rinon** [comment]
Yeah, it might be a bit tricky to get the right crate name, parsing the Cargo.toml if needed or whatever, but it should be possible.
