### ISSUE TITLE
Publish c2rust-bitfields?

### ISSUE THREAD

**Issue by Yoric** [immunant/c2rust#47]
`c2rust` produces code that depends on `c2rust-bitfields` for compilation, but that crate is only available on github. Perhaps it should be made available on crates.io?

**Comment by TheDan64** [comment]
We planned to do so, but hadn't yet decided on when exactly. I'll work on it early next week

**Comment by TheDan64** [comment]
This is now available on crates.io: https://crates.io/crates/c2rust-bitfields

**Comment by Yoric** [comment]
Thank you!
