### ISSUE TITLE
`docker_run.sh` never works

### ISSUE THREAD

**Issue by kkysen** [immunant/c2rust#502]
```shell
❯ ./docker/docker_run.sh 'immunant/c2rust:fedora-34-latest'
docker: Error response from daemon: Conflict. The container name "/c2rust" is already in use by container "cbc18536e85cc6d5de724b6a790b75dc6709c7f98c0fde460b80f263a11e777f". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
```

**Comment by thedataking** [comment]
I think the solution here is to `docker rm c2rust`. The idea is that `docker_run.sh` creates the container and you can connect to an already created container named c2rust using the `docker_exec.sh` script.  I think #503 would break the intended functionality of `docker_exec.sh`.

**Comment by kkysen** [comment]
Ah, I didn't realize that's how to fix that.  Could we add `docker rm c2rust` to `docker_run.sh` then?
