### ISSUE TITLE
Emit proper error when translating X86 intrinsics and when c2rust was built against LLVM 6

### ISSUE THREAD

**Issue by thedataking** [immunant/c2rust#51]
Issue #44 was resolved for LLVM 7 by adding support for additional intrinsics. If attempting to translate these with a c2rust build that uses LLVM 6, we should emit proper error messages to help the user understand the problem.

**Comment by rinon** [comment]
Better error messages implemented in 087181d

**Comment by thedataking** [comment]
Commit https://github.com/immunant/c2rust/commit/087181d62389df3a4dca337d1bfbd8c4d59855ad fixes the test suite, but I figured that we'd emit an error in the transpiler (on the C++ side) if we see intrinsics that we can't translate (because the transpiler was built against LLVM 6). Is this somehow not a problem?

**Comment by thedataking** [comment]
@TheDan64 I agree with your point that it might not be worth fixing for LLVM 6. How about we update known limitations (GitHub analytics shows its a page people actually read) to say something like  _LLVM 7 improves support for X86 intrinsics; if you are translating SIMD code, we recommend you use LLVM 7 or later_?

**Comment by TheDan64** [comment]
Yes, sounds good

**Comment by thedataking** [comment]
@TheDan64 since you are closer to the problem, can you suggest updated wording. What we have right now is kinda opaque and doesn't make it clear that newer LLVMs releases offer more support.

> Non x86/64 SIMD function/types and x86/64 SIMD function/types which have no rust equivalent

Happy to bikeshed new language if you post it here or send it on slack.

**Comment by TheDan64** [comment]
> Non x86/64 SIMD function/types and x86/64 SIMD function/types which have no rust equivalent

This isn't about newer LLVM support; it's about rust the language having an equivalent function to call.

> LLVM 7 improves support for X86 intrinsics; if you are translating SIMD code, we recommend you use LLVM 7 or later.

This is about newer LLVM support; is this not informative enough?
