### ISSUE TITLE
--emit-build-files emits incorrect Cargo.toml

### ISSUE THREAD

**Issue by skade** [immunant/c2rust#55]
The emitted Cargo.toml contains:

```
edition = 2018
```

but it must be:

```
edition = "2018"
```

**Comment by TheDan64** [comment]
Isn't this fixed in the latest commit? bdcf0711b9deae6b5144b1d4c28e0013d8ba454a

**Comment by skade** [comment]
Confirmed, it was committed after I pulled the last version. Thanks!
