### ISSUE TITLE
brew install c2rust

### ISSUE THREAD

**Issue by ankane** [immunant/c2rust#556]
Hi, just wanted to share that c2rust is now available on Homebrew, so Mac users can install it (and all its dependencies) with:

```sh
brew install c2rust
```

Homebrew precompiles binaries for both x86-64 and arm64, so installation is pretty much instant 🎉 

Ref: https://github.com/Homebrew/homebrew-core/pull/106484

**Comment by kkysen** [comment]
Thanks for adding this!  This is awesome!  We should be able to add this to our `README.md` now.

One question: how does this work with updating?  Is it tied to publishing a new version to crates.io/GitHub?

**Comment by ankane** [comment]
When a new tag is created on GitHub, a Homebrew community member or maintainer will typically update it. If you wanted to manually submit after releases, there's a `brew bump-formula-pr` command you can use.

**Comment by thedataking** [comment]
Thanks! This is great indeed. Small nitpick @ankane: I think https://github.com/immunant makes for a better URL than c2rust.com which is updated *very* infrequently and thus do not accurately reflect the current project state. Thanks again.

**Comment by carlocab** [comment]
> One question: how does this work with updating? Is it tied to publishing a new version to crates.io/GitHub?

You can also use [this action](https://github.com/dawidd6/action-homebrew-bump-formula) as part of your release workflow to automate submitting a pull request to homebrew-core.

**Comment by ankane** [comment]
The homepage has been updated: https://github.com/Homebrew/homebrew-core/pull/106553

**Comment by kkysen** [comment]
> You can also use [this action](https://github.com/dawidd6/action-homebrew-bump-formula) as part of your release workflow to automate submitting a pull request to homebrew-core.

Thanks @carlocab!  I don't think we currently have much of a release workflow as we don't do them too often, but we can add that once we improve the worflow.
