### ISSUE TITLE
Rust cross-checks are broken due to changes in rustc nightly

### ISSUE THREAD

**Issue by ahomescu** [immunant/c2rust#57]
The rustc nightly bump broke some things in our cross-checking crates, most notably due to the removal of `quote_expr!` and friends. I'll have to fix all the problems manually, including replacing all quoting macros with manual AST builder calls.

**Comment by thedataking** [comment]
Fixed.

**Comment by ahomescu** [comment]
Fixed by https://github.com/immunant/c2rust/commit/c2b17424a7bed1a11e5e954dcf93792ee4b8282f
