### ISSUE TITLE
`bear` generates empty `compile_commands.json` file

### ISSUE THREAD

**Issue by xobs** [immunant/c2rust#603]
The documentation says that `bear` can be used to generate `compile_commands.json` simply by placing it in front of the command. This does create a `compile_commands.json` file, however the file that is generated is empty:

```
user@Ondo:/opt/cfb$ rm compile_commands.json
user@Ondo:/opt/cfb$ bear clang -c crypto/curve25519/curve25519.c -o build/curve25519.o -Iinclude -DOPENSSL_32_BIT -Iextra_include
user@Ondo:/opt/cfb$ cat compile_commands.json
[]user@Ondo:/opt/cfb$
```

**Comment by kkysen** [comment]
I think this is an issue with [`bear`](https://github.com/rizsotto/Bear), not `c2rust`.  Depending on your version of `bear`, you might need a `--` before the command in `bear`.  Look at the `bear` `README.md`.

**Comment by xobs** [comment]
That doesn't work either, and at least produces an error:

```
user@Ondo:/opt/cfb$ bear -- clang -c crypto/curve25519/curve25519.c -o build/curve25519.o -Iinclude -DOPENSSL_32_BIT -Iextra_include
bear: Internal error.
Traceback (most recent call last):
  File "/usr/bin/bear", line 289, in wrapper
    return function(*args, **kwargs)
  File "/usr/bin/bear", line 316, in intercept_build
    exit_code, current = capture(args, tools)
  File "/usr/bin/bear", line 340, in capture
    exit_code = run_build(args.build, env=environment)
  File "/usr/bin/bear", line 213, in run_build
    exit_code = subprocess.call(command, *args, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--'
bear: Please run this command again and turn on verbose mode (add '-vvvv' as argument).
user@Ondo:/opt/cfb$
```

I was able to get my usecase working with `intercept-build sh -c`. I opened this issue more to note the fact that the `c2rust` `README.md` is incorrect, and the incantation given there does not seem to work as documented. If `bear` is no longer working, then it may make sense to remove it from `README.md`.

**Comment by kkysen** [comment]
You're running an old version of`bear`, as `bear` is now written in C++, not Python.  This issue is fully with `bear` and your environment, and we can't fully explain all the details of using old versions of `bear` in our `README.md`.  `bear` generally does work for everyone, so it doesn't make sense to remove it from our `README.md` at all.  Try updating `bear`, following `bear`'s documentation, and filing an issue with `bear` if this continues to be an issue.

**Comment by xobs** [comment]
Thanks for the update. The `bear` README says to install it from your package manager, and I thought that since I'm running Ubuntu 20.04 it would work. I didn't realize that it had diverged so far.

**Comment by kkysen** [comment]
Old `bear` should probably still work, but you're gonna have to find the old documentation, and I'm not sure they'll fix any bugs with the old version.
