### ISSUE TITLE
Feature request: Use more idiomatic `ptr` null pointer APIs instead of hardcoded 0s

### ISSUE THREAD

**Issue by 64kramsystem** [immunant/c2rust#620]
When c2rust transpiles null pointers, it uses hardcoded 0s converted to the dedicated types, eg.:

```rs
static mut demoptr: *mut i8 = 0 as *const i8 as *mut i8;
```

this is technically correct, however, using the dedicated `ptr` APIs leads to more readable and idiomatic code:

```rs
static mut demoptr: *mut u8 = ptr::null_mut();
```

(this applies only to `Sized` types, though)

**Comment by kkysen** [comment]
This was already discussed in #202.  There can be some subtle other differences between the two (https://github.com/immunant/c2rust/issues/202#issuecomment-1134932508), and when refactoring, both `0 as *mut _` and `ptr::null_mut()` would be removed in favor of non-raw pointer APIs, so the difference usually doesn't end up mattering so much.  Previous, this change could be done with the refactorer (`c2rust refactor`) (https://github.com/immunant/c2rust/issues/202#issuecomment-554853061), but that's now been deprecated as we're working on a more thorough way to lift unsafe Rust into safe Rust.
