### ISSUE TITLE
Allow whitelisting of flexible array members

### ISSUE THREAD

**Issue by thedataking** [immunant/c2rust#63]
We have two options here since we always need the programmer to make a determination:
1. update the sources to use C99-style flexible array members,
2. mark/whitelist non-C99 flexible array members in a configuration file.

The second option seems most appropriate in two cases:
- when tracking upstream C sources,
- when the non-C99 flexible array members are in system headers.

**Comment by thedataking** [comment]
We also have the option to assume that one-sized arrays at the end of structures are flex array members without breaking the translation. After some discussion, this was the approach we decided to take – plus adding a strict-flex-array-member mode that errors on one-sized potential.

**Comment by rinon** [comment]
I don't see a good reason to have a strict flex array member mode that errors on 1 sized arrays in the final slot. Why don't we just conservatively handle them as potentially flexible and emit slightly less readable code for that case?

**Comment by rinon** [comment]
Resolved by 1abf09f99fad528e78f53f10807c4c6411524642
