### ISSUE TITLE
Documentation request: Add python `compiledb` as a way to generate `compile-commands.json` from a `Makefile`

### ISSUE THREAD

**Issue by wildwestrom** [immunant/c2rust#659]
I was using c2rust and I was trying to translate this project called [light](https://github.com/haikarainen/light).
~~None of the methods from [the docs](https://c2rust.com/manual/quickstart.html?highlight=intercept#-with--intercept-build) to generate a compile-commands.json worked.~~ 
Turns out the other tools are just a bit more finicky (at least for the project I was working on).

[`compiledb`](https://pypi.org/project/compiledb/) works great.
All I had to do was `compiledb make` (after running `./autogen.sh && ./configure --with-udev` of course).

Could you please add this to the docs?

**Comment by thedataking** [comment]
Thanks for letting us know. I'm curious though that bear or intercept build did not work for you.  What versions did you try and what distro are you on (it looks like you're using Linux)?

As for `compiledb`, I've never used it. Would you be willing to open a PR with the desired changes to the docs?

**Comment by wildwestrom** [comment]
When I run any one of these:
```sh
# intercept-build
intercept-build sh -c "./autogen.sh && ./configure --with-udev && make"
./autogen.sh && ./configure --with-udev && intercept-build make
# bear
bear -- sh -c "./autogen.sh && ./configure --with-udev && make"
./autogen.sh && ./configure --with-udev && bear -- make
```

I get a compile_commands.json with:
```json
[]
```

I'm running Arch GNU/Linux.

```console
$ pip show scan-build
Name: scan-build
Version: 2.0.20
Summary: static code analyzer wrapper for Clang.
Home-page: https://github.com/rizsotto/scan-build
Author: László Nagy
Author-email: rizsotto@gmail.com
License: LICENSE.txt
Location: /home/main/.local/lib/python3.10/site-packages
Requires: 
Required-by: 
$ bear --version
bear 3.0.2
$ pip show compiledb
Name: compiledb
Version: 0.10.1
Summary: Tool for generating Clang JSON Compilation Database files for make-based build systems.
Home-page: https://github.com/nickdiego/compiledb
Author: Nick Yamane
Author-email: nick@diegoyam.com
License: GPLv3
Location: /home/main/.local/lib/python3.10/site-packages
Requires: bashlex, click, shutilwhich
Required-by: 
```

**Comment by kkysen** [comment]
Just to make sure, is this being run on a fresh build (after `make clean`)?

**Comment by wildwestrom** [comment]
Unfortunately, this particular project doesn't have a `make clean` command.

**Comment by wildwestrom** [comment]
> Just to make sure, is this being run on a fresh build (after `make clean`)?

That may have been the problem all along. So far the following commands work.
```sh
rm -f compile_commands.json && make clean
intercept-build sh -c "./autogen.sh && ./configure --with-udev && make"
```
```sh
rm -f compile_commands.json && make clean
bear -- sh -c "./autogen.sh && ./configure --with-udev && make"
```
These do not:
```sh 
rm -f compile_commands.json && make clean
./autogen.sh && ./configure --with-udev && intercept-build make
```
```sh
rm -f compile_commands.json && make clean
./autogen.sh && ./configure --with-udev && bear -- make
```

**Comment by kkysen** [comment]
What about a fresh build then?  Like right after `git clone`?  `bear` doesn't work if the compile commands are not actually run because they're already built.

**Comment by kkysen** [comment]
Okay, that's better.  I'm curious how `compiledb` is able to function without running the actual compile commands.

**Comment by wildwestrom** [comment]
`¯\_(ツ)_/¯`
