### ISSUE TITLE
`c2rust` fails to build with LLVM 15

### ISSUE THREAD

**Issue by jrmuizel** [immunant/c2rust#676]
```shell
 --- stderr
  CMake Warning:
    Manually-specified variables were not used by the project:

      CMAKE_ASM_COMPILER
      CMAKE_ASM_FLAGS


  * Closing connection 0
  * Closing connection 1
  /Users/jrmuizel/.cargo/git/checkouts/c2rust-2a3ef4c32beab81a/1fddfc4/c2rust-ast-exporter/src/AstExporter.cpp:2270:52: error: no member named 'Ascii' in 'clang::StringLiteral::StringKind'
              case clang::StringLiteral::StringKind::Ascii:
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
  1 error generated.
  make[3]: *** [CMakeFiles/clangAstExporter.dir/AstExporter.cpp.o] Error 1
  make[2]: *** [CMakeFiles/clangAstExporter.dir/all] Error 2
  make[1]: *** [CMakeFiles/clangAstExporter.dir/rule] Error 2
```

**Comment by kkysen** [comment]
On Linux it builds with LLVM 11 and 12 fine.  I haven't tested LLVM 15 before.

You're getting this same error for LLVM 11, 12, and 15 but not 13 and 14?

**Comment by jrmuizel** [comment]
I didn't have 13 and 14 so didn't try them. The error seems to be the same in 11, 12 and 15. Using LLVM 8 worked though. 

I was using:
```
LLVM_CONFIG_PATH=/usr/local/opt/llvm/bin/llvm-config cargo install --git https://github.com/immunant/c2rust.git c2rust
LLVM_CONFIG_PATH=/usr/local/opt/llvm@11/bin/llvm-config cargo install --git https://github.com/immunant/c2rust.git c2rust
LLVM_CONFIG_PATH=/usr/local/opt/llvm@15/bin/llvm-config cargo install --git https://github.com/immunant/c2rust.git c2rust
```

**Comment by thedataking** [comment]
I'm not able to reproduce with LLVM 11, 12 on Linux (Ubuntu 22.10) or LLVM 11 on MacOS Monterey. I did however find something interesting looking at the definition of `clang::StringLiteral::StringKind`in [Expr.h](https://github.com/llvm/llvm-project/blob/8b1b0d1d81213d10e6add52d93d0afd71baf6a04/clang/include/clang/AST/Expr.h#L1789). It seems that the `Ascii` variant was renamed to `Ordinary` at some point so I think we need to check if that is what's happening on your machine.

Are you able to run down the exact copy of `Expr.h` you are building against? Also, what is your default version of `llvm`?

**Comment by thedataking** [comment]
@jrmuizel can you try `LLVM_CONFIG_PATH=/usr/local/opt/llvm@15/bin/llvm-config cargo build` on `feature/llvm-15.0.0` and let me know if that works. I'm hitting a weird linker issue on MacOS to I switched to link dynamically instead of statically. 

With static linking on MacOS, I'm seeing this error related to `-opaque-pointers` (see change in `build.rs.`):
```
ld: in /usr/local/Cellar/llvm/15.0.0/lib/libclangAST.a(Stmt.cpp.o), could not parse object file /usr/local/Cellar/llvm/15.0.0/lib/libclangAST.a(Stmt.cpp.o): 'Opaque pointers are only supported in -opaque-pointers mode (Producer: 'LLVM15.0.0' Reader: 'LLVM APPLE_1_1400.0.29.102_0')', using libLTO version 'LLVM version 14.0.0, (clang-1400.0.29.102)' for architecture x86_64
```

**Comment by pmembrey** [comment]
@thedataking I tried the `feature/llvm-15.0.0` branch and I was able to build it successfully with `cargo build`. I'm using version `15.0.1` of llvm on an M1 Mac.

In case it helps someone, on an M1 Mac, homebrew uses `/opt/homebrew/` as its default location. I used this command to build:

```
LLVM_CONFIG_PATH=/opt/homebrew/Cellar/llvm/15.0.1/bin/llvm-config cargo build
```
