### ISSUE TITLE
Current main branch regression: panic when the wrong command is invoked

### ISSUE THREAD

**Issue by 64kramsystem** [immunant/c2rust#721]
With the stable version, if a wrong c2rust command is invoked, the help is displayed.

With the current main branch, the program panics instead:

```shell
$ c2rust pizza compile_commands.json

thread 'main' panicked at 'no entry found for key', c2rust/src/main.rs:144:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1286ee23e4e2dec8c1696d3d76c6b26d97bbcf82/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/1286ee23e4e2dec8c1696d3d76c6b26d97bbcf82/library/core/src/panicking.rs:65:14
   2: core::panicking::panic_display
             at /rustc/1286ee23e4e2dec8c1696d3d76c6b26d97bbcf82/library/core/src/panicking.rs:139:5
   3: core::panicking::panic_str
             at /rustc/1286ee23e4e2dec8c1696d3d76c6b26d97bbcf82/library/core/src/panicking.rs:123:5
   4: core::option::expect_failed
             at /rustc/1286ee23e4e2dec8c1696d3d76c6b26d97bbcf82/library/core/src/option.rs:1879:5
   5: c2rust::main
```

Version: `C2Rust unknown (fe79581ef 2022-11-07) dirty 1 modification`

**Comment by kkysen** [comment]
That's weird.   The panic here on the indexing, https://github.com/immunant/c2rust/blob/fe79581ef60031990ef7f51d81390149ada07363/c2rust/src/main.rs#L141-L144, shouldn't happen because there shouldn't be a `clap` match unless the subcommand name exists, so I'm not sure what's happening here yet.

**Comment by kkysen** [comment]
@64kramsystem, I think it should work now in #722.

**Comment by 64kramsystem** [comment]
> @64kramsystem, I think it should work now in #722.

Thanks! Tried the command again and it now doesn't crashes :+1:
