### ISSUE TITLE
Incorrect type alias generated from `curl/lib/setopt.c`

### ISSUE THREAD

**Issue by thedataking** [immunant/c2rust#74]
Generated:
```Rust
pub type CURLU = Curl_URL;
```

Expected (insofar that it allows compilation to proceed):
```Rust
pub type CURLU = crate::urlapi::Curl_URL;
```

**Comment by rinon** [comment]
The actual error here is that `*mut CURLU` is unsized:

    error[E0277]: the size for values of type `setopt::Curl_URL` cannot be known at compilation time
        --> src/setopt.rs:5823:43
         |
    5823 |         10282 => { (*data).set.uh = param.arg::<*mut CURLU>() }
         |                                           ^^^ doesn't have a size known at compile-time
         |
         = help: the trait `std::marker::Sized` is not implemented for `setopt::Curl_URL`
         = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
         = note: required because of the requirements on the impl of `core::ffi::sealed_trait::VaArgSafe` for `*mut setopt::Curl_URL`

We should implement `VaArgSafe` for raw pointers to unsized types, but this will need to be upstreamed.

**Comment by rinon** [comment]
Blocked on upstream compiler support, see https://github.com/rust-lang/rust/pull/61126
