### ISSUE TITLE
Structs which are both packed and aligned fail to compile

### ISSUE THREAD

**Issue by TheDan64** [immunant/c2rust#75]
For example, the linux headers have this struct:

```c
struct xregs_state {
    struct fxregs_state i387;
    struct xstate_header header;
    u8 extended_state_area[0];
} __attribute__ ((packed, aligned(64)));
```

Which will fail to compile when translated due to being `#[repr(C, packed, align(64)]` but a struct cannot be packed and aligned in rust. This is blocked on https://github.com/rust-lang/rust/issues/59154

**Comment by ahomescu** [comment]
Fixed in https://github.com/immunant/c2rust/commit/49d2b577a39d7d13f93468347cd3f235e0644c77.
