### ISSUE TITLE
static analysis does not support `wrapping_sub` or `wrapping_add`

### ISSUE THREAD

**Issue by aneksteind** [immunant/c2rust#785]
in line with #734 and #746, we'd like to be able to support something like the following:
```rust
unsafe extern "C" fn connections_get_new_connection(
    mut srv: *mut server,
    ...
) -> *mut connection {
    (*srv).lim_conns = ((*srv).lim_conns).wrapping_sub(1); // <--- currently causes a panic
```

**Comment by aneksteind** [comment]
@kkysen this might be a good one for you

**Comment by kkysen** [comment]
> @kkysen this might be a good one for you

I can take a look at this.

Is the plan to special case all functions called from `std`?  Or is there a way to reduce them to the `core::intrinsics::*` ones, perhaps (of which this one, `wrapping_sub`, and the previous, `size_of`, are)?

**Comment by aneksteind** [comment]
> Is the plan to special case all functions called from std? Or is there a way to reduce them to the core::intrinsics::* ones, perhaps (of which this one, wrapping_sub, and the previous, size_of, are)?

I'd like @spernsteiner to weigh in on this

**Comment by spernsteiner** [comment]
>Is the plan to special case all functions called from std? Or is there a way to reduce them to the core::intrinsics::* ones, perhaps (of which this one, wrapping_sub, and the previous, size_of, are)?

I think we should have one case for "unknown function that doesn't take or return any pointers", which we can assume does nothing interesting for analysis purposes, and then separately special-case each pointer-related library function that `c2rust-transpile` uses in its output.  `wrapping_sub` and `size_of` would fall into the former case.  For the latter case, I think `c2rust-transpile` only uses a relatively small number of functions which are all fairly simple, so special-casing each of them shouldn't be overly burdensome.

In some cases it may be possible to inspect the MIR bodies of library functions, but I think we should try to avoid that complexity if possible.

**Comment by aneksteind** [comment]
@spernsteiner  unless I'm missing something I think there is a third category that doesn't fall into the doesn't-take-or-return-pointers set or the output-by-c2rust set, which we are now seeing as a transpiler artifact for functions in other modules, but could theoretically still be present. Modulo fixing the transpiler's output to use those modules, are you suggesting we skip third party calls with pointers altogether? Is it useful to work with just the signature without visiting the body?

**Comment by spernsteiner** [comment]
For calls between C compilation units, I think we should either fix the transpiler or else do symbol resolution in the static analysis so we can match up calls with callees (when both are in the current crate, but use `extern "C"` due to transpiler limitations).

**Comment by kkysen** [comment]
> I think we should have one case for "unknown function that doesn't take or return any pointers", which we can assume does nothing interesting for analysis purposes

@spernsteiner, so for any library function (no matter the origin), if it takes and returns no pointers, we just skip it/do no analysis, such as in the `u32::wrapping_sub`, but not for something like `ptr::wrapping_sub`, right?  I'll open an issue for that and fix that first, which should handle a bunch of cases, like this one above.

> and then separately special-case each pointer-related library function that `c2rust-transpile` uses in its output. `wrapping_sub` and `size_of` would fall into the former case. For the latter case, I think `c2rust-transpile` only uses a relatively small number of functions which are all fairly simple, so special-casing each of them shouldn't be overly burdensome.

I think the problem with this approach is that we want lifting to be incremental.  Thus, there will also be other already lifted (automatic by us, but also human-lifted) code using any number of other library functions.  What do we plan to do with these?

> In some cases it may be possible to inspect the MIR bodies of library functions, but I think we should try to avoid that complexity if possible.

I was thinking maybe we could do this for a limited number of functions, specifically ones that are `const` or `#[inline]`, as the compiler is already going to look at the bodies of those during calls, and thus they wouldn't be marked on excessively complex functions.



> unless I'm missing something I think there is a third category that doesn't fall into the doesn't-take-or-return-pointers set or the output-by-c2rust set, which we are now seeing as a transpiler artifact for functions in other modules, but could theoretically still be present. Modulo fixing the transpiler's output to use those modules, are you suggesting we skip third party calls with pointers altogether? Is it useful to work with just the signature without visiting the body?

@aneksteind, do you mean the `extern "C" { ... }` functions that are defined in the same crate in other modules and are an artifact of C headers?  I agree we should try to resolve all of those, either in the transpiler, or in the static analysis itself, and if the latter, it should suggest rewrites that import them properly.
