### ISSUE TITLE
static analysis erroneously wants to visit MIR bodies of extern function calls

### ISSUE THREAD

**Issue by aneksteind** [immunant/c2rust#793]
Running static analysis on the following results in an exception

```rust
extern "C" {
    // ...
    fn foreign(r: *mut bar);
    // ...
}

unsafe extern "C" fn func(mut b: *mut bar) {
    // ...
    foreign(b);
    // ...
}
```

```
thread 'rustc' panicked at 'not yet implemented: call to unknown function DefId(0:66 ~ main[5047]::{extern#0}::foreign)', c2rust-analyze/src/dataflow/type_check.rs:353:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
``` 

In [`visit_call_other`](https://github.com/immunant/c2rust/blob/212dfa970fbd760db963e0eabc8b8ee5d1eb296b/c2rust-analyze/src/dataflow/type_check.rs#L345) we might at least like to iterate over the function signature to relate pointer permissions.

**Comment by kkysen** [comment]
> we might at least like to iterate over the function signature to relate pointer permissions.

What do you mean by relating pointer permissions using only the signature?

**Comment by aneksteind** [comment]
> What do you mean by relating pointer permissions using only the signature?

E.g. when there is a function call there is a terminator with `_dest = call(_arg1, ..., _argN)` and static analysis calls `do_assign` for those [arguments](https://github.com/immunant/c2rust/blob/212dfa970fbd760db963e0eabc8b8ee5d1eb296b/c2rust-analyze/src/dataflow/type_check.rs#L364) and for the [output](https://github.com/immunant/c2rust/blob/212dfa970fbd760db963e0eabc8b8ee5d1eb296b/c2rust-analyze/src/dataflow/type_check.rs#L371) of the call. We miss out on those relationships if the call doesn't have an MIR body to traverse, as things currently stand.

**Comment by kkysen** [comment]
Split into:
* #842
* #843
