### ISSUE TITLE
Issue with running cargo install in Mac

### ISSUE THREAD

**Issue by mahajpuneet** [immunant/c2rust#813]
Trying the below, aint working(Apple Mac M1 chip, homebrew installed rust):

```shell
LLVM_CONFIG_PATH=/opt/homebrew/opt/llvm/bin/llvm-config cargo install --git https://github.com/immunant/c2rust.git c2rust

`error: failed to run custom build command for `c2rust-ast-exporter v0.17.0 (/Users/300075517/.cargo/git/checkouts/c2rust-2a3ef4c32beab81a/f265192/c2rust-ast-exporter)`

Caused by:
  process didn't exit successfully: `/var/folders/c6/0xcy5jb51vs0t8jh6w17363dhr3nlr/T/cargo-installxK3TKi/release/build/c2rust-ast-exporter-6f6bf204c7d3a6e9/build-script-build` (exit status: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_aarch64-apple-darwin = None
  CMAKE_TOOLCHAIN_FILE_aarch64_apple_darwin = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_aarch64-apple-darwin = None
  CMAKE_GENERATOR_aarch64_apple_darwin = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_aarch64-apple-darwin = None
  CMAKE_PREFIX_PATH_aarch64_apple_darwin = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_aarch64-apple-darwin = None
  CMAKE_aarch64_apple_darwin = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "/Users/300075517/.cargo/git/checkouts/c2rust-2a3ef4c32beab81a/f265192/c2rust-ast-exporter/src" "-DCMAKE_OSX_ARCHITECTURES=arm64" "-DLLVM_DIR=/opt/homebrew/Cellar/llvm/15.0.7_1/lib/cmake/llvm" "-DClang_DIR=/opt/homebrew/Cellar/llvm/15.0.7_1/lib/cmake/clang" "-DCMAKE_INSTALL_PREFIX=/var/folders/c6/0xcy5jb51vs0t8jh6w17363dhr3nlr/T/cargo-installxK3TKi/release/build/c2rust-ast-exporter-6850e0f1b3ec04b7/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -arch arm64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -arch arm64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -arch arm64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Release"
  -- The C compiler identification is AppleClang 14.0.0.14000029
  -- The CXX compiler identification is AppleClang 14.0.0.14000029
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring incomplete, errors occurred!
  See also "/private/var/folders/c6/0xcy5jb51vs0t8jh6w17363dhr3nlr/T/cargo-installxK3TKi/release/build/c2rust-ast-exporter-6850e0f1b3ec04b7/out/build/CMakeFiles/CMakeOutput.log".

  --- stderr
  CMake Error at /opt/homebrew/Cellar/cmake/3.25.2/share/cmake/Modules/ExternalProject.cmake:2677 (message):
    git version 1.6.5 or later required for --recursive flag with 'git
    submodule ...': GIT_VERSION_STRING=''
  Call Stack (most recent call first):
    /opt/homebrew/Cellar/cmake/3.25.2/share/cmake/Modules/ExternalProject.cmake:2794 (_ep_get_git_submodules_recurse)
    /opt/homebrew/Cellar/cmake/3.25.2/share/cmake/Modules/ExternalProject.cmake:4185 (_ep_add_download_command)
    CMakeLists.txt:18 (ExternalProject_Add)


  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 1`
```

**Comment by kkysen** [comment]
Can you try updating `git`?

**Comment by mahajpuneet** [comment]
Thanks @kkysen , I did update but getting this post update:

error: failed to run custom build command for `c2rust-ast-exporter v0.17.0 (/Users/300075517/.cargo/git/checkouts/c2rust-2a3ef4c32beab81a/f265192/c2rust-ast-exporter)`

Caused by:
  process didn't exit successfully: `/var/folders/c6/0xcy5jb51vs0t8jh6w17363dhr3nlr/T/cargo-installeHpGAw/release/build/c2rust-ast-exporter-6f6bf204c7d3a6e9/build-script-build` (exit status: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_aarch64-apple-darwin = None
  CMAKE_TOOLCHAIN_FILE_aarch64_apple_darwin = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_aarch64-apple-darwin = None
  CMAKE_GENERATOR_aarch64_apple_darwin = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_aarch64-apple-darwin = None
  CMAKE_PREFIX_PATH_aarch64_apple_darwin = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_aarch64-apple-darwin = None
  CMAKE_aarch64_apple_darwin = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "/Users/300075517/.cargo/git/checkouts/c2rust-2a3ef4c32beab81a/f265192/c2rust-ast-exporter/src" "-DCMAKE_OSX_ARCHITECTURES=arm64" "-DLLVM_DIR=/opt/homebrew/Cellar/llvm/15.0.7_1/lib/cmake/llvm" "-DClang_DIR=/opt/homebrew/Cellar/llvm/15.0.7_1/lib/cmake/clang" "-DCMAKE_INSTALL_PREFIX=/var/folders/c6/0xcy5jb51vs0t8jh6w17363dhr3nlr/T/cargo-installeHpGAw/release/build/c2rust-ast-exporter-6850e0f1b3ec04b7/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -arch arm64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -arch arm64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -arch arm64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Release"
  -- The C compiler identification is AppleClang 14.0.0.14000029
  -- The CXX compiler identification is AppleClang 14.0.0.14000029
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring incomplete, errors occurred!
  See also "/private/var/folders/c6/0xcy5jb51vs0t8jh6w17363dhr3nlr/T/cargo-installeHpGAw/release/build/c2rust-ast-exporter-6850e0f1b3ec04b7/out/build/CMakeFiles/CMakeOutput.log".

  --- stderr
  CMake Error at /opt/homebrew/Cellar/cmake/3.25.2/share/cmake/Modules/ExternalProject.cmake:2677 (message):
    git version 1.6.5 or later required for --recursive flag with 'git
    submodule ...': GIT_VERSION_STRING=''
  Call Stack (most recent call first):
    /opt/homebrew/Cellar/cmake/3.25.2/share/cmake/Modules/ExternalProject.cmake:2794 (_ep_get_git_submodules_recurse)
    /opt/homebrew/Cellar/cmake/3.25.2/share/cmake/Modules/ExternalProject.cmake:4185 (_ep_add_download_command)
    CMakeLists.txt:18 (ExternalProject_Add)


  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 1

  build script failed, must exit now', /Users/300075517/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.49/src/lib.rs:1104:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to compile `c2rust v0.17.0 (https://github.com/immunant/c2rust.git#f2651921)`, intermediate artifacts can be found at `/var/folders/c6/0xcy5jb51vs0t8jh6w17363dhr3nlr/T/cargo-installeHpGAw`

**Comment by kkysen** [comment]
For some reason, it seems `cmake` is failing to detect the correct `git` executable on your machine.  I'd usually suspect it's cached, but `cargo install` uses a new install directory every time, so I'm not sure.

**Comment by thedataking** [comment]
@mahajpuneet c2rust builds correctly on macOS systems with M1 and M2 processors. If you have recent xcode tools installed, that should provide you with a recent version of git. Therefore, the problem is likely with your environment as @kkysen is has pointed out. 

I recommend you create a new user account on your Mac without any sort of customization beyond installing the bare minimum c2rust prerequisites (`brew install llvm python3 cmake openssl`) and see if that resolves your issue. 

I hope that is able to get you unstuck as we are unable to provide you with additional support due to our limited resources.
