### ISSUE TITLE
Gentoo Building

### ISSUE THREAD

**Issue by Uramekus** [immunant/c2rust#84]
Gentoo's LLVM doesn't provide static libs due to being "a security flaw and waste of time"

http://lists.llvm.org/pipermail/llvm-dev/2015-September/090589.html

c2rust actually fails to build on gentoo and i'm needing to use an arch crhoot to build it then move the binary around to my Gentoo system.

the rpcs3 devs had this problem and they fixed it creating a  DUSE_SHARED_LLVM_LIBS=ON/OFF toggle and naming exactly which components they need
https://github.com/RPCS3/rpcs3/pull/3404/commits/6f33953861430882d318b6b96f7e59b06b6a4d4c

**Comment by rinon** [comment]
C2Rust can and does link against the LLVM & Clang shared libraries if available (we do this on Arch which also only ships shared library versions of `libclang*`). It sounds like a different problem may be preventing this. I'll spin up a gentoo container and check, but I'll have to wait till LLVM compiles... ;)

**Comment by Uramekus** [comment]
oh, didn't knew arch didn't ship lLLVM too, I would check stuff around before posting the issue if i knew that (my bad, i was naive to assume they didnt since it does build fine there)


so that's probably a bug due to slotting because to even start building i need to specify the  LIBCLANG_PATH="/usr/lib/llvm/9/lib64".

Gonna seach more about that on my side too, maybe its profile seeding, or missing a var import.
thanks for the fast response!!!

**Comment by Uramekus** [comment]
Raw output of the error for debugging linked here: https://pastebin.com/raw/L0gdUgin

**Comment by rinon** [comment]
Ahhh, ok, gentoo doesn't build the combined `libLLVM.so` that most platforms provide. This can be fixed in our build system by querying `llvm-config` properly.

**Comment by rinon** [comment]
Should be fixed in ee9f6782b7ce8769c8197c40b6497aee5b94a547 on master, could you test? You'll still need to set `LIBCLANG_PATH` because of a clang-sys bug. Clang-sys should query `llvm-config` on where to find `libclang.so` but it doesn't when dynamically linking. You will also need the right `llvm-config` in your path or you will need to set `LLVM_CONFIG_PATH` to the path to `llvm-config`.

**Comment by Uramekus** [comment]
yeah, it works now as long as you specify the `LIBCLANG_PATH`

thanks for your help/work dude, also, you should put that on the readme.md 

Closing.

**Comment by thedataking** [comment]
@Uramekus thanks for confirming. Good point w.r.t. the README, it now mentions the need to set `LIBCLANG_PATH` on Gentoo.

**Comment by zserik** [comment]
thx. I noticed another thing:
c2rust fails to build if LLVM+clang is build using clang+libcxx, but the default compiler is gcc.
It works if I specifiy:
```sh
CC="/usr/lib/llvm/8/bin/clang" CXX="/usr/lib/llvm/8/bin/clang++"
```
additional to the env vars from the `README` (otherwise it fails to correctly link some C++ files, ...)

but I needed to apply another patch
```patch
diff --git a/c2rust-ast-exporter/build.rs b/c2rust-ast-exporter/build.rs
index 802db607..e383f7fe 100644
--- a/c2rust-ast-exporter/build.rs
+++ b/c2rust-ast-exporter/build.rs
@@ -175,7 +175,7 @@ fn build_native(llvm_info: &LLVMInfo) {
     }
 
     // Link against the C++ std library.
-    if cfg!(target_os = "macos") {
+    if cfg!(any(target_os = "macos", target_os = "linux")) {
         println!("cargo:rustc-link-lib=c++");
     } else {
         println!("cargo:rustc-link-lib=stdc++");
```

otherwise it returns the following error:
```
  = note: /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /tmp/cargo-install6M6W4U/release/deps/libc2rust_ast_exporter-68f741f2f194a6a3.rlib(AstExporter.cpp.o): undefined reference to symbol '_ZNKSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE7compareEmmPKcm'
          /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libc++.so.1: error adding symbols: DSO missing from command line
```

It should be possible (e.g. via a feature?) to opt-in using libcxx.
