### ISSUE TITLE
builtin handling for string functions expects wrong arguments

### ISSUE THREAD

**Issue by dberlin** [immunant/c2rust#857]
Attempts to convert strchr/strrchr (and some others in that list) will fail with a panic in convert_libc_fns, say "`convert_libc_fns` must have exactly 3 arguments: [dst, c, len]""

Length does not exist, strchr/strrchr is a 2 argument function :)
It actually should just work fine if you translate the 2 argument ones straight through.

I'll make a patch.

**Comment by fw-immunant** [comment]
Interestingly, 4062985 which expanded the support from "mem" functions (which do share a prototype) to "str" ones including unary `strdup` and `strlen` as well as binary `strndup`, `strnlen`, and `strchr`/`strrchr`, did not update the handling that expected all such libc functions to be ternary with `[dst, c, len]`.

Thanks for noticing this--I'll try to put together a test case to validate the changes before I properly submit a review, but from a quick look they seem reasonable. I'll follow up with tweaks for unary functions.
