### ISSUE TITLE
c2rust-analyze: use rvalue_tys for all casts

### ISSUE THREAD

**Issue by spernsteiner** [immunant/c2rust#878]
On lighttpd, our largest source of panics is the `Rvalue::Cast` case in `AnalysisCtxt::type_of_rvalue`.  Only a few kinds of casts are handled here; otherwise, it asserts that there are no pointer types in the cast's target type.  Separately, casts of the constant `0` to a pointer type are supported because `main.rs` adds an entry to `acx.rvalue_tys` for each such cast.  Having an `rvalue_tys` entry causes the entire `type_of_rvalue` `Cast` case to be bypassed in favor of the `LTy` stored in that entry.

We should change the analysis to add `rvalue_tys` entries for all `Cast`s, and we should move the restrictions on cast kinds and input/output types, which are currently implemented partly in `main.rs` and partly in `type_of_value`, into `dataflow::type_check`.  This will make cast handling more uniform, and should make it easier to add support for additional cast kinds later on.  This should also let us provide more specific panic messages for unsupported casts, which will make it easier to classify the various kinds of unsupported casts in lighttpd.

**Comment by kkysen** [comment]
Is this at all similar to your feedback here: https://github.com/immunant/c2rust/pull/839#discussion_r1115160479?

**Comment by fw-immunant** [comment]
Should this be closed now that #883 has merged? cc @aneksteind

**Comment by kkysen** [comment]
I believe so.
