### ISSUE TITLE
(`c2rust-analyze`) Support all ways of writing `addr_of!` during rewriting

### ISSUE THREAD

**Issue by kkysen** [immunant/c2rust#912]
During rewriting, `std::ptr::addr_of!` seems to be special cased to an extent, as some other equivalent forms do not work.  Specifically, these work:

* [x] `std::ptr::addr_of!`
* [x] `::std::ptr::addr_of!`
* [ ] `use std::ptr::addr_of`, `addr_of!`
   This one wasn't working previously, but seems to be working now.  It may be finicky.
* [x] `core::ptr::addr_of!`
* [ ] `::core::ptr::addr_of!`
* [ ] `use core::ptr::addr_of`, `addr_of!`

See also https://github.com/immunant/c2rust/blob/11bf3514929133cd5ee44fe4eb5956bb0e4c07e8/c2rust-analyze/tests/analyze/string_casts.rs#L18-L21

There doesn't appear to be a specific error.  Instead, this is printed:

```sh
error: aborting due to previous error

For more information about this error, try `rustc --explain E0433`.
Error: ErrorGuaranteed(())
```

**Comment by aneksteind** [comment]
Can you be more specific about what "doesn't work" means? Error messages would be helpful

**Comment by kkysen** [comment]
Yeah, I'll add them.

**Comment by kkysen** [comment]
Hmm, it seems that now `use std::ptr::addr_of; addr_of!(x);` works?  In a new, separate test from `master`, but I don't think I touched anything related.
