### ISSUE TITLE
rewriter: hypothetical lifetime parameters not added to types in function signatures

### ISSUE THREAD

**Issue by oinoom** [immunant/c2rust#921]
For a function signature such as 
```rust
fn foo<'d>(ra: &'d mut A<'d>, ppd: *mut *mut Data<'d>) {
```

If hypothetical lifetimes are introduced for `ppd: &'h0 &'h1 Data<'d>`and `Data` gets a hypothetical lifetime and updated to `Data<'d, 'h2>` we'd like the rewriter to generate:

```rust
fn foo<'d, 'h0, 'h1, 'h2>(ra: &'d mut A<'d>, ppd: &'h0 &'h1 Data<'d, h2>) {
```

**Comment by kkysen** [comment]
Sure.  What's the current behavior of the rewriter?

**Comment by aneksteind** [comment]
It avoids lieftime rewrites for all non-field types

**Comment by aneksteind** [comment]
I'm working on this, so assigning just myself for the time being
