### ISSUE TITLE
New and reparsed ASTs don't match

### ISSUE THREAD

**Issue by TheDan64** [immunant/c2rust#96]
I'm trying to run the refactorer on an entire crate with the `--cargo` flag and I'm running into this panic: `'new and reparsed ASTs don't match: Path(None, path(Self)) vs ImplicitSelf'`

**Comment by rinon** [comment]
What codebase can I reproduce this on?

**Comment by TheDan64** [comment]
It happened on nginx

**Comment by rinon** [comment]
@TheDan64 do you know if this is still happening? We've fixed several of these already.

**Comment by TheDan64** [comment]
No clue; I haven't touched nginx in a while. I haven't seen it elsewhere, though.

**Comment by rinon** [comment]
This seems stale, we can open a new issue if we encounter it again.

**Comment by TheDan64** [comment]
Sounds good. Yeah, I haven't been able to repro it since
