### ISSUE TITLE
Potentially out-of-bounds array accesses don't count for return values

### ISSUE THREAD

**Issue by Serentty** [immunant/c2rust#98]
This C code compiles to the Rust code below.

```#include <stdint.h>

int get_nth(int array[], size_t n)
{
    return array[n];
}
```

```
#![allow(dead_code,
         mutable_transmutes,
         non_camel_case_types,
         non_snake_case,
         non_upper_case_globals,
         unused_mut)]
#![feature(libc)]
extern crate libc;
#[no_mangle]
pub unsafe extern "C" fn get_nth(mut array: *mut libc::c_int,
                                 mut n: libc::c_int) -> libc::c_int {
    compile_error!("Reached end of non-void function without returning");
}
```

Unless I'm missing something, this C code isn't undefined behaviour unless it is called with an index that is out of bounds for the provided array, yet the generated Rust code makes no attempt to access the value from the array, and instead gives an error about reaching the end of the function without returning anything.

**Comment by rinon** [comment]
I just tested this on master and it seems to have been fixed. Were you testing this with the version 0.10.1 on crates.io or the demo version on the website?

    pub unsafe extern "C" fn get_nth(mut array: *mut libc::c_int, mut n: size_t)
     -> libc::c_int {
        return *array.offset(n as isize);
    }

**Comment by Serentty** [comment]
I was testing it using the demo version on the website. I wasn't aware that that was out of date. If that's the case, it's good to know that this has already been fixed.

**Comment by Serentty** [comment]
I'll leave this open just in case I'm missing something. Feel free to close it.

**Comment by rinon** [comment]
Thanks for pointing this out, we'll get the website updated.

**Comment by rinon** [comment]
Closing, will track website update on #100 since it's taking awhile.
