### ISSUE TITLE
Refactorer: No-op ast rewriting makes modifications when proc macro derives are present

### ISSUE THREAD

**Issue by TheDan64** [immunant/c2rust#99]
I wrote a short no-op traversal script in lua:
```lua
refactor:transform(
    function(transform_ctx, crate)
        return transform_ctx:visit_fn_like({}, crate)
    end
)
```

The input object, `{}` has no methods so it isn't modifying the ast in any way (and is being applied only to functions).

When running it on the nginx source, I see structs get modified:

```rust
#[derive ( Copy , Clone )]
#[repr(C)]
pub struct ngx_str_t {
    pub len: size_t,
    pub data: *mut u_char,
}
#[derive ( BitfieldStruct , Clone , Copy )]
#[repr(C)]
pub struct ngx_connection_s {
    // ...
}
```

becomes 

```rust
#[repr(C)]#[derive(Copy, Clone)]
pub struct ngx_str_t {
    pub len: size_t,
    pub data: *mut u_char,
}
#[repr(C)]#[derive(BitfieldStruct, Clone, Copy)]
pub struct ngx_connection_s {
    // ...
}#[derive(BitfieldStruct, Clone, Copy)]
impl ngx_connection_s {
    #[doc = r" This method allows you to write to a bitfield with a value"]
    pub fn set_buffered(&mut self, int: libc::c_uint) {
        fn zero_bit(byte: &mut u8, n_bit: u64) {
            let bit = 1 << n_bit;
            *byte &= !bit as u8;
        }
```
The issue being that 1) code generated by the `BitfieldStruct` proc macro is being dumped into the source file which causes errors about duplicate methods and 2) the derive attrs are being applied to the aforementioned dumped impl

**Comment by TheDan64** [comment]
An easy way to reproduce this without compiling the entirety of nginx is to only build its `src/main.rs`/`src/core/nginx.rs`

**Comment by rinon** [comment]
Yeah... not surprising. We don't really handle proc macros at all. I'm not sure we even can know what tokenstream produced the output, and we certainly don't know what AST produced the output to revert to that (since there isn't one).

**Comment by rinon** [comment]
Nevermind, proc macros do get expanded during macro expansion, so we should handle them. Looks like this is just a bug in the collapser.

**Comment by rinon** [comment]
Should be fixed by 4e737b6615b7ea891159397d4e220492bc3f4f2a.

**Comment by TheDan64** [comment]
I think this has been fixed - I haven't run into it after rebasing. Shall I release a 0.1.1 of bitfields then? So that this is readily accessible

**Comment by rinon** [comment]
Yeah, I think we should release 0.1.1.
